### ISSUE TITLE
Not running javascript when using proxy

### ISSUE THREAD

**Issue by jl-DaDar** [scrapy-plugins/scrapy-splash#103]
i am using scrapy_splash to crawl pages that requires js to retrieve proper content.

Everything is fine when I use SplashRequest without proxy settings, but when I put in proxy settings, the javascript would not render, giving me prejavascript html content which do not have the data I need.

Does anyone know how to solve this? I am sure the proxy ip are not blacklisted.

**Comment by kmike** [comment]
@cooldar how are you setting up the proxy?

**Comment by jl-DaDar** [comment]
nevermind, i think I figured it out. The proxy is really slow, had to set max wait time 10 sec for it to work most of the time.

**Comment by jl-DaDar** [comment]
thanks tho!! appreciate your help

**Comment by kmike** [comment]
I'm glad you've solved it!
