### ISSUE TITLE
No way to slow down the scrapy speed?

### ISSUE THREAD

**Issue by Sraw** [scrapy-plugins/scrapy-splash#104]
In README.rst, it only says the `DOWNLOAD_DELAY` will behave in unexpected way, but no alternative suggestion.

So how to control the crawling speed while using splash?

**Comment by Sraw** [comment]
Um... It seems I was wrong about something. Sorry about this useless issue.

**Comment by Sraw** [comment]
I have tried many ways to solve this problem but failed.
I am using `scrapy_splash.SplashRequest`, and `DOWNLOAD_DELAY` is still not working.

**Comment by kmike** [comment]
@Sraw DOWNLOAD_DELAY can work in an unexpected way if you're _not_ using scrapy-splash, and use Splash HTTP API directly instead.

Could you please give a more detailed example - what are you trying to acheive?

**Comment by Sraw** [comment]
@kmike Actually, I do use scrapy-splash but still get an unexpected behavior.
```
yield SplashRequest(url, self.parse_page,
                                endpoint='render.html',
                                args={'wait': 0.4},
                            )
```
and `setting.py` of scrapy:
```
...somthing like BOT_NAME...
DOWNLOAD_DELAY = 3
SPLASH_URL = 'http://127.0.0.1:8050'

DOWNLOADER_MIDDLEWARES = {
    'scrapy_splash.SplashCookiesMiddleware': 723,
    'scrapy_splash.SplashMiddleware': 725,
    'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 810,
}

SPIDER_MIDDLEWARES = {
    'scrapy_splash.SplashDeduplicateArgsMiddleware': 100,
}

DUPEFILTER_CLASS = 'scrapy_splash.SplashAwareDupeFilter'
HTTPCACHE_STORAGE = 'scrapy_splash.SplashAwareFSCacheStorage'
```
I guess the problem is about middlewares?

**Comment by kmike** [comment]
How did you check that DOWNLOAD_DELAY doesn't work?

**Comment by Sraw** [comment]
@kmike I set it to 1000. Means only one request every 1000 seconds. But it still sends request with no delay.

**Comment by kmike** [comment]
@Sraw by default DOWNLOAD_DELAY is per-domain; are all requests to the same domain?

**Comment by Sraw** [comment]
@kmike yes that all requests are similar with this style "*.domain.com/search/xxxx/px". The "domain.com" is fixed.

**Comment by kmike** [comment]
@Sraw by default Scrapy uses full netloc as a key, so foo.domain.com and bar.domain.com have separate concurrency limits. 

I think you can fix it by setting SPLASH_SLOT_POLICY to scrapy_splash.SlotPolicy.SINGLE_SLOT.

**Comment by Sraw** [comment]
@kmike I'm sorry about to annoy you. This is truly a problem about scrapy itself and are exactly connected to the full nectloc.
Thanks very much.
