### ISSUE TITLE
response.real_url does not exist in my environment

### ISSUE THREAD

**Issue by zperfet** [scrapy-plugins/scrapy-splash#110]
When i run the example(quotes.py) code, an error " AttributeError: 'TextResponse' object has no attribute 'real_url'" appears. i do not know why.

**Comment by zperfet** [comment]
I used to pass the url of my target website to my parse funtion, then i find that i can not use real_url. But today i find that i can just do it by changing endpint. But how to use real_url or if it can still be used?

**Comment by kmike** [comment]
@bjtuzpf I can't reproduce it with example quotes.py script.
What are versions of Splash and scrapy-splash you're using?
Have you modified the example?

**Comment by zperfet** [comment]
I'm sorry, i just found that i was wrong.I changed url to my target website, but it just do not use splash at all.

**Comment by kmike** [comment]
Thanks for clarifying it!
