### ISSUE TITLE
TypeError: SplashJsonResponse url must be str, got unicode 

### ISSUE THREAD

**Issue by wenxzhen** [scrapy-plugins/scrapy-splash#111]
My Splash version is in 2.3.2:

> 2017-03-23 10:24:49.591255 [-] Splash version: 2.3.2
> 2017-03-23 10:24:49.592435 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1, Lua 5.2
> 2017-03-23 10:24:49.592688 [-] Python 3.4.3 (default, Nov 17 2016, 01:08:31) [GCC 4.8.4]
> 2017-03-23 10:24:49.592960 [-] Open files limit: 99999
> 2017-03-23 10:24:49.593182 [-] Can't bump open files limit
> 2017-03-23 10:24:49.703665 [-] Xvfb is started: ['Xvfb', ':1', '-screen', '0', '1024x768x24', '-nolisten', 'tcp']
> 2017-03-23 10:24:49.911082 [-] proxy profiles support is enabled, proxy profiles path: /etc/splash/proxy-profiles
> 2017-03-23 10:24:50.651053 [-] verbosity=1
> 2017-03-23 10:24:50.651382 [-] slots=50
> 2017-03-23 10:24:50.651615 [-] argument_cache_max_entries=500
> 2017-03-23 10:24:50.652616 [-] Web UI: enabled, Lua: enabled (sandbox: enabled)
> 2017-03-23 10:24:50.659033 [-] Site starting on 8050
> 2017-03-23 10:24:50.659403 [-] Starting factory <twisted.web.server.Site object at 0x7f332408a240>

While my Scrapy splash is in 0.7.1, and run with Python 2.7 as described below. Is it an issue in the python version?

> 2017-03-23 19:10:05 [scrapy.core.scraper] ERROR: Error downloading <GET http://192.168.6.115:8050/render.json>
> Traceback (most recent call last):
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1301, in _inlineCallbacks
>     result = g.send(result)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 53, in process_response
>     spider=spider)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy_splash/middleware.py", line 387, in process_response
>     response = self._change_response_class(request, response)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy_splash/middleware.py", line 402, in _change_response_class
>     response = response.replace(cls=respcls, request=request)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/http/response/text.py", line 50, in replace
>     return Response.replace(self, *args, **kwargs)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/http/response/__init__.py", line 79, in replace
>     return cls(*args, **kwargs)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy_splash/response.py", line 95, in __init__
>     super(SplashJsonResponse, self).__init__(*args, **kwargs)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy_splash/response.py", line 33, in __init__
>     super(_SplashResponseMixin, self).__init__(url, *args, **kwargs)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/http/response/__init__.py", line 21, in __init__
>     self._set_url(url)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/http/response/__init__.py", line 43, in _set_url
>     type(url).__name__))
> TypeError: SplashJsonResponse url must be str, got unicode:

Thanks,

**Comment by wenxzhen** [comment]
appreciate if anyone can advice why the URL in the Splash response is encoded in unicode?

**Comment by kmike** [comment]
@wenxzhen how can we reproduce it? Could you provide a small example?

**Comment by wenxzhen** [comment]
I am just running the Splash(standalone) + Scrapy-Cluster(Scrapy-Flash) and then run a spider to have a try.
From the JSON dump, I found some of the payloads are encoded in Unicode.

**Comment by wenxzhen** [comment]
@kmike With the Scrapy_Splash, from the wireshark capture, I see the request to Splash was in something wrong. 

Since the Scrapy_Splash is working as a proxy to Splay, the request should be in POST with extra meta? But I can only see the GET request without any meta info.

![scrapy_splash_not_work](https://cloud.githubusercontent.com/assets/2071967/24352278/89d1b12c-131b-11e7-8428-948ab27876ed.jpg)

Any hints?

**Comment by wenxzhen** [comment]
oh, I see the main problem lies in the Scrapy-Cluster, it reads the request from the Redis Queue and compose the Request object again by itself without respect to the original request type

**Comment by damienkilgannon** [comment]
@wenxzhen @kmike I am seeing this same problem ... however, I checked the request which is going to Splash and it is as it should be. 

```
2017-06-08 10:57:48.612662 [-] "172.18.0.1" - - [08/Jun/2017:10:57:48 +0000] "POST /execute HTTP/1.1" 200 2545 "-" "Baiduspider+(+http://www.baidu.com/search/spider.htm)"

2017-06-08 10:59:13.612828 [events] {"maxrss": 120716, "active": 0, "fds": 21, "args": {"url": "http://www.testsite.co.uk/", "lua_source": "function main(splash) local url = splash.args.url assert(splash:go(url)) assert(splash:wait(2)) splash:runjs(\"javascript:enterSite(0)\") assert(splash:wait(3)) return {cookies = splash:get_cookies()} end", "magic_response": True, "headers": {"User-Agent": "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en"}, "timeout": 60, "cookies": [], "uid": 140376349983016}, "qsize": 0, "rendertime": 12.325340986251831, "status_code": 200, "_id": 140376349983016, "method": "POST", "path": "/execute", "timestamp": 1496919553, "load": [0.26, 0.2, 0.18], "client_ip": "172.18.0.1", "user-agent": "Mozilla/5.0 (compatible; MJ12bot/v1.2.4; http://www.majestic12.co.uk/bot.php?+)"}
```

**Comment by wenxzhen** [comment]
I think you are not using the SplashRequest option, am I right?

**Comment by Gallaecio** [comment]
@wenxzhen Did you ever manage to fix or work around this issue? Could you share a URL to reproduce the issue?
