### ISSUE TITLE
How to scrap next page's url link

### ISSUE THREAD

**Issue by ranafge** [scrapy-plugins/scrapy-splash#112]
Hello i am new in programming and scrapy. Trying to learn scrapy i try scrap some items. but unable to do the scrap next page url to scrap items, please help how to grap next page url link for this web site. 

Here is my code:

    import scrapy
    from scrapy.linkextractors import LinkExtractor 

    

    class BdJobs(scrapy.Spider):
		name = 'bdjobs'
		allowed_domains = ['BdJobs.com']
		start_urls = [
					  'http://jobs.bdjobs.com/',
					  'http://jobs.bdjobs.com/jobsearch.asp?fcatId=8&icatId='
					  ]
		#rules=( Rule(LinkExtractor(allow()), callback='parse', follow=True))

		def parse(self, response):
			for title in response.xpath('//div[@class="job-title-text"]/a'):
				yield {
				'titles': title.xpath('./text()').extract()[0].strip()
				}

        nextPageLink:		

        for grab the next page url here is the inspect Element url:
        https://08733078838609164420.googlegroups.com/attach/58c611bdb536b/bdjobs.png?part=0.1&view=1&vt=ANaJVrEDQr4PODzoOkFRO_fLhL2ZF3x-Mts4XJ8m8qb2RSX1b4n6kv0E-62A2yvw0HkBjrmUOwCrFpMBk_h8UYSWDO6hZXyt-N2brbcYwtltG-A6NiHeaGc

    Here is output:

    
    {"titles": "Senior Software Engineer (.Net)"},
    {"titles": "Java programmer"},
    {"titles": "VLSI Design Engineer (Japan)"},
    {"titles": "Assistant Executive (Computer Lab-Evening programs)"},
    {"titles": "IT Officer, Business System Management"},
    {"titles": "Executive, IT"},
    {"titles": "Officer, IT"},
    {"titles": "Laravel PHP Developer"},
    {"titles": "Executive - IT (EDISON Footwear)"},
    {"titles": "Software Engineer (PHP/ MySQL)"},
    {"titles": "Software Engineer [Back End]"},
    {"titles": "Full Stack Developer"},
    {"titles": "Mobile Application Developer (iOS/ Android)"},
    {"titles": "Head of IT Security Operations"},
    {"titles": "Database Administrator, Senior Analyst"},
    {"titles": "Infrastructure Delivery Senior Analyst, Network Security"},
    {"titles": "Head of IT Support Operations"},
    {"titles": "Hardware Engineer"},
    {"titles": "JavaScript/ Coffee Script Programmer"},
    {"titles": "Trainer - Auto CAD"},
    {"titles": "ASSISTENT PRODUCTION OFFICER"},
    {"titles": "Customer Relationship Executive"},
    {"titles": "Head of Sales"},
    {"titles": "Sample Master"},
    {"titles": "Manager/ AGM (Finance & Accounts)"},
    {"titles": "Night Aiditor"},
    {"titles": "Officer- Poultry"},
    {"titles": "Business Analyst"},
    {"titles": "Sr. Executive - Sales & Marketing (Sewing Thread)"},
    {"titles": "Civil Engineer"},
    {"titles": "Executive Director-HR"},
    {"titles": "Sr. Executive (MIS & Internal Audit)"},
    {"titles": "Manager, Health & Safety"},
    {"titles": "Computer Engineer (Diploma)"},
    {"titles": "Sr. Manager/ Manager, Procurement"},
    {"titles": "Specialist, Content"},
    {"titles": "Manager, Warranty and Maintenance"},
    {"titles": "Asst. Manager - Compliance"},
    {"titles": "Officer/Sr. Officer/Asst. Manager (Store)"},
    {"titles": "Manager, Maintenance (Sewing)"}

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.
