### ISSUE TITLE
Proxy servers do not work with Scrapy-Splash

### ISSUE THREAD

**Issue by eusid** [scrapy-plugins/scrapy-splash#117]
http://stackoverflow.com/questions/43090352/proxy-servers-with-scrapy-splash

Can someone please tell me why this is not working, or if it works at all? I have consulted all available documentation on the issue.  I'd really like to use Scrapy-Splash with proxies.

**Comment by eusid** [comment]
Also, I am using crawlera middleware. I am going to try manually setting proxy on each request. I disabled crawlera middleware, and setup a proxy profile for Splash and this is working. I think I need to move this to crawlera

**Comment by kmike** [comment]
It seems you've figured this out. To use Splash with Crawlera you can't use crawlera middleware; use method described at https://doc.scrapinghub.com/crawlera.html#using-crawlera-with-splash instead.

**Comment by eusid** [comment]
Does setting up proxy profile and passing it into args not work? I'd much rather do it that way than having to put a LUA script in my code.  Is there an easy way I can check that splash is indeed using the proxy?

**Comment by kmike** [comment]
An easy way to check if Splash using a proxy is to fetch https://httpbin.org/ip via Splash and check the IP address.

Proxy profile should work, but doing it in a script is a bit better. The problem is that by default all requests (to main page, css/js files, etc.) look unrelated to Crawlera, so they will be fetched from different IP addresses. To use a single slave to fetch all what's on a page (like a regular user does) it is better to use crawlera sessions; Lua script sets up this crawlera session.

**Comment by eusid** [comment]
ok, thanks for the explanation. will change back to using script.

**Comment by kmike** [comment]
Here is a more elaborate script: https://github.com/scrapy-plugins/scrapy-splash/issues/97#issuecomment-268647494 - it combines example from scrapy-splash docs and an example from Crawlera docs.

**Comment by khpeek** [comment]
I also can't get Scrapy with Splash to work with a proxy. I've documented my attempts using Scrapy-Splash's `example` project here:

https://stackoverflow.com/questions/45039850/how-to-use-scrapy-with-both-splash-and-tor-over-privoxy-in-docker-compose

When I set the `http_proxy` environment variable to enable the `HttpProxyMiddleware`, I start getting 500 Internal Server Errors. I've also tried setting the same proxy for Splash following https://splash.readthedocs.io/en/stable/api.html?#proxy-profiles, but to no avail (see also https://stackoverflow.com/questions/45037258/500-internal-server-error-when-combining-scrapy-over-splash-with-an-http-proxy).

How can I get Scrapy-Splash to work with a proxy in these simple examples (without Crawlera or Lua scripts)?

**Comment by eusid** [comment]
in my experience even if you get it it to work with the LUA script it drops all the additional requests for resources after the initial http request at random it seems. i thought maybe something was going on with the session. i made sure to set it. i was using crawlera.
