### ISSUE TITLE
Use a custom scrapy.Request subclass instead of a meta key

### ISSUE THREAD

**Issue by kmike** [scrapy-plugins/scrapy-splash#12]
Maybe it could work like FormRequest? 

This won't work for https://github.com/scrapinghub/scrapyjs/issues/11, but with a custom request class / request creation function the user won't be required to add middleware, dupefilter, etc. to settings; also, API could be nicer.

**Comment by pablohoffman** [comment]
I like this idea, I think it would make the "javascript on scrapy" feel like a better supported feature. I'd imagine it'll also help for a more robust scripting API (by validating lua scripts at request creation time, for example).

**Comment by kmike** [comment]
There is now SplashRequest.
