### ISSUE TITLE
how to set splash timeout

### ISSUE THREAD

**Issue by JhonSmith0x7b** [scrapy-plugins/scrapy-splash#123]
I run a splash server in the docker.
commond: `docker run  -p 8050:8050 scrapinghub/splash --max-timeout 3600`
But I got a 504 error.
`"error": {"info": {"timeout": 30}, "description": "Timeout exceeded rendering page", "error": 504, "type": "GlobalTimeoutError"}`

Although I try to add `splash.resource_timeout`, `request:set_timeout` and `SPLASH_URL = 'http://localhost:8050?timeout=1800.0'`, nothing changed.
Thanks for help.

**Comment by kmike** [comment]
The intended way is to use `SplashRequest(url, self.parse, args={'timeout': 1800, ...})` - does it work for you?

**Comment by JhonSmith0x7b** [comment]
@kmike  Yes, thank u!

**Comment by vionemc** [comment]
It doesn't work for me. I got error 400

**Comment by garylab** [comment]
@vionemc The max value of timeout is `90`, here is the doc: https://splash.readthedocs.io/en/stable/api.html#render-html
