### ISSUE TITLE
Splash Time out Issue

### ISSUE THREAD

**Issue by ijharulislam** [scrapy-plugins/scrapy-splash#128]
Here is my Lua script. I am getting time out error. 

```
treat = require("treat")
function main(splash)
  local url = splash.args.url
  assert(splash:go(url))
  local links = splash:select_all('a[onclick]')
  count = 1
  local results = {}
  for i, v in ipairs( links ) do
    splash:go(url)
    local links = splash:select_all('a[onclick]')
    obj = {}
    count = count + 1
    links[i]:click()
    obj["html"] = splash:html()
    obj["url"] = splash:evaljs("window.location.href")
    results[#results+1] = obj
 
  end
  return {
    html = splash:html(),
    results = treat.as_array(results),
    count = count
  }
end
```

Here is the error message. 
```
{
    "error": 504,
    "type": "GlobalTimeoutError",
    "description": "Timeout exceeded rendering page",
    "info": {
        "timeout": 60
    }
}
```

**Comment by kmike** [comment]
For such scripts you should start splash with a larger `--max-timeout` value, and increase value of `timeout` argument. See http://splash.readthedocs.io/en/stable/api.html#arg-timeout and http://splash.readthedocs.io/en/stable/faq.html#i-m-getting-lots-of-504-timeout-errors-please-help for more.

**Comment by ijharulislam** [comment]
Hi kmike,
I subscribed a small instance of Splash. I am not using docker. How to set max-timeout for remote splash server?
I am trying to pass as args. But it is not working.

args={'lua_source': script, 'max-timeout':3600}

**Comment by garylab** [comment]
I change my request to :
```python
    def start_requests(self):
        for url in self.start_urls:
            request = SplashRequest(url,
                                    self.parse,
                                    args={'wait': 1, 'timeout': 90, 'images': 0},
                                    cookies=get_cookies()
                                    )
            yield request
```
and it works!

**Comment by clesauln** [comment]
You could adjust settings of your process / spider with increase download timeout :
https://docs.scrapy.org/en/latest/topics/settings.html#download-timeout
