### ISSUE TITLE
Set max-timeout to remote Splash server

### ISSUE THREAD

**Issue by ijharulislam** [scrapy-plugins/scrapy-splash#129]
I bought a small instance of Splash. I am not using docker. How to set max-timeout for remote splash server?
I am trying to pass as args. But it is not working.

args={'lua_source': script, 'max-timeout':3600}

**Comment by kmike** [comment]
It is not possible to set max-timeout for a remote server, this is by design. You need to either contact the support of your Splash provider to raise the limit, run Splash yourselves, or split a script into several scripts. An advanage of splitting a script is that it can run in parallel this way.
