### ISSUE TITLE
How to handle 302, 301 Page redirecttion

### ISSUE THREAD

**Issue by ijharulislam** [scrapy-plugins/scrapy-splash#134]
There is a website redirects url and It seems that splash can't handle that. How to handle 302, 301 status in splash?

**Comment by kmike** [comment]
Could you please give an example? Splash should handle redirects fine (do a redirect), like a browser; there are tests for this.

**Comment by ijharulislam** [comment]
Try with this url
http://www.toyoko-inn.com/hotel/00264/index.html

The url redirects to
https://www.toyoko-inn.com/search/detail/00264/

**Comment by kmike** [comment]
I just tried it in Splash (both 3.0 and 2.3.3), and it redirects to this detail page fine for me. Does it work for you in Splash, without scrapy-splash? What are you expecting?

**Comment by ijharulislam** [comment]
Thanks for your reply. It is working.

**Comment by kmike** [comment]
Do you mean Splash works, but you have issues with scrapy-splash? Or is everything working, and we can close this ticket?

**Comment by dzenli** [comment]
Hi @kmike , 
When I click link likes `<a href=".. " target="_blank">` which contain target="_blank" in firefox browser,  it will open the link in a new tab.  I used splash click this link and splash not render the new link. I know that splash is a single tab browser, so is there a way to force the new link which contain target="-blank" always open in current tab? Look forward to your kind reply. Thanks.

**Comment by kmike** [comment]
@dzenli that's a good question; I don't know a "proper' solution, but you may try removing this target="_blank" attribute via JS before clicking.

I'm closing this ticket; feel free to reopen if there is additional information available.
