### ISSUE TITLE
add option to return Htmlresponse generated from content of 'html' key in splash response

### ISSUE THREAD

**Issue by pawelmhm** [scrapy-plugins/scrapy-splash#14]
When processing splash response we could just replace response from splash with new HTMLResponse generated from html in splash response. This way user will not have to worry about generating Html response in spider callback, she can just forget about js rendering - when splash will be enabled she will just get normal target response with JS rendered (with proper url, html etc). User can just use normal response.xpath on this response without doing anything extra. I think rendering html would probably be most common use case for splash middleware so it's worth enabling this by default.

If there will be some other keys in splash response (other then html) we could pass them in meta perhaps? .har content could be converted to response headers

**Comment by kmike** [comment]
Hey @pawelmhm - there is now some magic in scrapy-splash master branch which sets response.body, response.url, response.headers, handles cookies and allows to use response.xpath on JSON splash responses; check the updated README. Feedback is welcome!

**Comment by kmike** [comment]
This should be fixed.
