### ISSUE TITLE
Non-html content type returns 502

### ISSUE THREAD

**Issue by p8a** [scrapy-plugins/scrapy-splash#140]
I am trying to build a generic crawler to capture a HAR containing the URL with all its referenced resources - some of which may be binary. The problem I'm running into is if the original URL returns content type other than HTML I get a 502 error back and I cannot figure out how to get pass that, I would like to get a HAR back regardless.

Crawler code using plash, scrapy and scrapy-splash:
`

     for url in self._urls:
            splash_args = {
                'png': 1,
                'har': 1,
                'width': 600,
                'wait': 0.5,
                'headers': {}
            }
            splash_args['headers']['User-Agent'] = USER_AGENT
            splash_args['headers']['Accept-Language'] = LOCALE_EN
            yield SplashRequest(url, self.parse_result, endpoint='render.json',
                                args=splash_args,
                                slot_policy=SlotPolicy.SCRAPY_DEFAULT)
`

Crawling for https://download.sysinternals.com/files/ProcessExplorer.zip results in 

`
[scrapy.spidermiddlewares.httperror] INFO: Ignoring response <502 https://download.sysinternals.com/files/ProcessExplorer.zip>: HTTP status code is not handled or not allowed
`

Any suggestions how to fix it ? Thanks

**Comment by rohitkoganti** [comment]
Hi, 

I'm having the same issue. Did you figure out the reason why? Thanks.

**Comment by Gallaecio** [comment]
@p8a, @rohitkoganti Does it work without Splash?

**Comment by appleshowc** [comment]
I'm having the same issue.
When I use `SplashRequest`, it returns 502 or 504
When I use `scrapy.Request`, it works fine and returns 200
