### ISSUE TITLE
mac works, but Ubuntu not

### ISSUE THREAD

**Issue by shaunrong** [scrapy-plugins/scrapy-splash#141]
Hey, 

Sorry to bother you again. I was able to run my codes with scrapy-splash on Mac, everything was fine.

Then I thought about deploying the same codes on a Ubuntu server. I have docker, docker-machine all installed, splash was running. Then it always popped the following error messages:

`ERROR: Error downloading <GET http://pubs.rsc.org/en/journals/journalissues/an#!issueid=an140001&type=current&issnprint=0003-2654 via http://192.168.99.100:8050/render.html>: Connection was refused by other side: 111: Connection refused.`

I checked online. I thought it might be the firewall problem. So I specifically added port 8050 to the iptables:

```
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  wappa.mit.edu        anywhere             tcp dpt:ssh
ACCEPT     tcp  --  128.3.0.0/16         anywhere             tcp dpt:ssh
ACCEPT     tcp  --  128.3.0.0/16         anywhere             tcp dpt:27017
ACCEPT     tcp  --  131.243.220.0/22     anywhere             tcp dpt:ssh
ACCEPT     tcp  --  131.243.220.0/22     anywhere             tcp dpt:27017
ACCEPT     tcp  --  18.0.0.0/8           anywhere             tcp dpt:27017
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8050

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:8050

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

```

Do you have some clues what might went wrong? Any help is appreciated. Thank you.

**Comment by shaunrong** [comment]
Somehow I got it working with aquarium. I don't know why...

**Comment by shaunrong** [comment]
Somehow I got it working all right with [Aquarium](https://github.com/TeamHG-Memex/aquarium). I don't know why...

**Comment by kmike** [comment]
On Ubuntu it is likely Docker IP address is not 192.168.99.100 as in example, it is more likely to be 127.0.0.1. But anyways, before running scrapy-splash it is good to check that Splash address you're providing work: either visit it in a browser, or fetch content using curl/wget, e.g. `http://<splash-address>:8050/_ping`.
