### ISSUE TITLE
HTTPS proxy does not support

### ISSUE THREAD

**Issue by Miando** [scrapy-plugins/scrapy-splash#143]
When I try add httpS proxy, it not working
`args={
                    'proxy': 'https://35.185.80.76:3128',
}`

`Bad request to Splash: {'info': {'type': 'bad_argument', 'argument': 'proxy', 'description': 'Invalid proxy URL format.'}, 'description': 'Incorrect HTTP API arguments', 'error': 400, 'type': 'BadOption'}
`
May be need use other way? Thanks

**Comment by kmike** [comment]
Use `http://...` both for http and https proxies - see http://splash.readthedocs.io/en/stable/api.html#arg-proxy. This protocol here is just a convention to choose between socks and http[s]; whether to use http or https depends on a web site you're fetching. HTTPS should work this way if your proxy supports it.

**Comment by Miando** [comment]
Thank you for response, but it does not working. I tried this proxy without splash and have recived some data, but when I set this http proxy with splash, I have 'Access denied'.

**Comment by kmike** [comment]
Do you know who returns this Access denied response? I don't think http vs https may cause it. If it is a web site, you may try using e.g. a different User-Agent. Tools like Wireshark can be helpful to check the difference between traffic issued by Splash and by your browser.

**Comment by Miando** [comment]
Извиняюсь, я только учу англ. мог не правильно донести информацию. Суть в том, что когда я без прокси, через браузер захожу по ссылке, вижу `Access Denied
You don't have permission to access`, устанавливаю прокси, вижу нормальный сайт. Со scrapy точно также. когда пробую добавить аргумент в Splash`args={
                    'proxy': 'http://35.185.80.76:3128'}` возвращает тело  `Access Denied
You don't have permission to access`
Еще раз спасибо за ответы

**Comment by Miando** [comment]
Дело было в User-Agent. Спасибо еще раз, извиняюсь что голову морочил
