### ISSUE TITLE
Ecnoding Error

### ISSUE THREAD

**Issue by ijharulislam** [scrapy-plugins/scrapy-splash#145]
Hi,
I am using Scrapy-splash render.json endpoint. Some times I am getting this error.
I saw similar issue on another thread but did not find any solution.
https://github.com/scrapy-plugins/scrapy-splash/issues/107

`TypeError: __init__() got an unexpected keyword argument 'encoding' `

**Comment by Gallaecio** [comment]
Please, close this issue, it’s a duplicate of the linked issue. The issue has been fixed, but a new version of scrapy-splash has not been released since. You might want to try with the `master` branch.

**Comment by ijharulislam** [comment]
@Gallaecio 
Ok. Thanks.
