### ISSUE TITLE
how to get status code other than 200 from scrapy-splash

### ISSUE THREAD

**Issue by 3xp10it** [scrapy-plugins/scrapy-splash#146]
I am trying to get request status code with scrapy and scrapy-splash,below is spider code.
```
class Exp10itSpider(scrapy.Spider):
    name = "exp10it"

    def start_requests(self):
        urls = [
                'http://192.168.8.240:8000/xxxx' 
        ]
        for url in urls:
            #yield SplashRequest(url, self.parse, args={'wait': 0.5, 'dont_redirect': True},meta={'handle_httpstatus_all': True})
            #yield scrapy.Request(url, self.parse, meta={'handle_httpstatus_all': True})
            yield scrapy.Request(url, self.parse, meta={'handle_httpstatus_all': True,'splash': {
                'args': {
                    'html': 1,
                    'png': 1,
                    }
            }
            }
            )


    def parse(self, response):
        input("start .........")
        print("status code is:\n")
        input(response.status)
```

My start url `http://192.168.8.240:8000/xxxx` is a 404 status code url,there are threee kinds of request way upon:

the first is:

`yield SplashRequest(url, self.parse, args={'wait': 0.5, 'dont_redirect': True},meta={'handle_httpstatus_all': True})`

the second is:

`yield scrapy.Request(url, self.parse, meta={'handle_httpstatus_all': True})`

the third is:
```
            yield scrapy.Request(url, self.parse, meta={'handle_httpstatus_all': True,'splash': {
                'args': {
                    'html': 1,
                    'png': 1,
                    }
            }
            }
            )
```

Only the second request way `yield scrapy.Request(url, self.parse, meta={'handle_httpstatus_all': True})` can get the right status code `404`,the first and the third both get status code `200`,that's to say,after I try to use scrapy-splash,I can not get the right status code `404`,can you help me?

**Comment by Gallaecio** [comment]
Please, close this issue. [It has been answered on StackOverflow](https://stackoverflow.com/a/46843447/939364).
