### ISSUE TITLE
SplashRequest missing errback parameter

### ISSUE THREAD

**Issue by verzola** [scrapy-plugins/scrapy-splash#147]
Is it possible to pass a callback to handle errors like the errback parameter of scrapy.http.Request?

https://doc.scrapy.org/en/0.10.3/topics/request-response.html#scrapy.http.Request

**Comment by jing-code4value** [comment]
Just encountered the same issue today. Workaround is to create SplashRequest first and then set errback:
        spash_request = SplashRequest(request_url, normal_callback_func)
        spash_request.errback = error_callback_func

**Comment by kmike** [comment]
The parameter is not in a argument list, but SplashRequest supports **kwargs which are passed to scrapy.Request constructor. It means workaround shouldn't be needed, you can set errback just like for scrapy.Request.
