### ISSUE TITLE
Caching issue?

### ISSUE THREAD

**Issue by deathemperor** [scrapy-plugins/scrapy-splash#148]
I installed splash and got it running at http://localhost:8050 with ease.

The problem is:
- When I try rendering this page https://shopee.com.my/Women's-Clothing-cat.16 the FIRST time it shows fine below
![OK](https://i.snag.gy/ke5WKY.jpg) 
- But when I do it again it couldn't render the page correctly. Notice the differences in UI and a lot of red requests that seem to be errors but no information.
![NOT OK](https://i.snag.gy/Lc2tfa.jpg) 

I've also attached the HAR data here https://pastebin.com/K63CMWQ5

But if I restart docker container of splash and run it again it works fine. In fact, If I restart docker before every run it works 100% of the time.

I also notice that if I run it with error, then do nothing for a few min (about 5m+), it works again.

This happens only with this website. The site uses React. I tried other React sites it works fine.

Is it about cache control?

**Comment by Gallaecio** [comment]
Does the behavior only happen when using scrapy-splash? Otherwise, please close this issue and report it on https://github.com/scrapinghub/splash
