### ISSUE TITLE
section in readme.rst with solutions for common issues

### ISSUE THREAD

**Issue by iAnanich** [scrapy-plugins/scrapy-splash#161]
I wasted my day in frustration why does splash/scrapy-splash/ randomly decides to render or not, and then tried to set `wait: 5`...

And as I discovered it is a pretty common issue. So I'm proposing to add something like `FAQ` or `Troubleshooting` section in the `README.rst` file to help newcomers use this great plugin. Also, mention such things as `Splash`&`Scrapy` documentation and their help-pages.

- [x] StackOverflow
- [x] Scrapy bugs reporting
- [x] Splash FAQ
- [ ] `wait` argument

**Comment by iAnanich** [comment]
@kmike is there any rules for getting help with `scrapy-splash`, like "ask on StackOverflow" or something?

**Comment by kmike** [comment]
Hey @iAnanich! There are no rules, but probably stackoverflow is the best. Currently most documentaion is in Splash - e.g., as you said, there is Splash FAQ with a list of common workarounds: http://splash.readthedocs.io/en/stable/faq.html#website-is-not-rendered-correctly. 

+1 to add more information to README, maybe some links. 

It may also be a right time to split README into several files and move to readthedocs; it is too long, and while everything is documented, docs are not organized well, and it is rather hard to get started and understand best practices.

**Comment by iAnanich** [comment]
about linking StackOverflow `[splash-scrapy]` tag: is it better to give a hyper-reference to `active` tab or to `votes` tab or any other ideas?
