### ISSUE TITLE
Injecting anti headless browser detection script

### ISSUE THREAD

**Issue by vionemc** [scrapy-plugins/scrapy-splash#167]
https://intoli.com/blog/making-chrome-headless-undetectable/

If you see there, they provide a script to avoid getting detected that we are using a headless browser. Some sites are okay to be scraped using a standard request, but not okay to be scraped using a Splash Request.  It will show a captcha request. So I want to use the script injection. But, is it possible?

Thanks

**Comment by kmike** [comment]
Splash provides [splash:autoload](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-autoload) function which allows to execute JS before a web page starts to run its own JS.
