### ISSUE TITLE
Can't convert object: depth limit is reached error

### ISSUE THREAD

**Issue by dzlab** [scrapy-plugins/scrapy-splash#17]
I'm having a [Can't convert object: depth limit is reached](https://github.com/scrapinghub/splash/blob/master/splash/lua.py#l127) error as showing below

```
==> default: 2015-04-22 12:52:01.126719 [-] ('enrich_from_lua_error', ScriptError(ValueError("Can't convert object: depth limit is reached",),), LuaError(u'ValueError("Can\'t convert object: depth limit is reached",)',))
```

Here is my scrapy/splash code:

``` python
def start_requests(self):
        script = """
        function main(splash)
            assert(splash:go(splash.args.url))
            splash:wait(20.0)
            return splash:evaljs("document.querySelectorAll('p.MSMRSTSignature_FullName.MSMRSTArticleItemTitle')")
        end
        """
        for url in self.start_urls:
            yield Request(url, self.parse, meta={
                'splash': {
                    'endpoint': 'execute',
                    'args': {'lua_source': script}
                }
            })
```

When I try my javascript code in chrome console a I get about 77 `p` elements with nested elements.
How I could fix this?

**Comment by kmike** [comment]
The problem is that document.querySelectorAll returns a NodeList with references to DOM elements, and they effectively contain the whole DOM tree. Splash tries to serialize it, but stops earlier because the result is very deep (100+ levels of nesting).

I think the best way is to prepare data you want to extract in JS code and return a "clean" object with data, without references to DOM elements.

In future Splash will provide more high-level utilities for extracting data from HTML, but they are not ready yet.

**Comment by dzlab** [comment]
it seems a lot for debugging: javascript inside lua inside python :(
any sample to see how it looks like a javascript code to pass to `splash:evaljs`?

**Comment by kmike** [comment]
> it seems a lot for debugging: javascript inside lua inside python :(

yeah, and JS is behind QT which is behind PyQT's sip C++ wrappers :)

> any sample to see how it looks like a javascript code to pass to splash:evaljs?

You can use innerHTML/outerHTML/innerText. For complex expressions it may be easier to use [splash:jsfunc](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-jsfunc) - add your own helpers as needed. For example, you can write something like the following (untested):

``` lua
get_nodes_html = splash:jsfunc([[
    function(css){
        var elems = document.querySelectorAll(css);
        var res = [];
        for (var i=0; i<elems.length; i++){
            res.push(elems[i].outerHTML);
        }
        return res;
    }
]])

local res = get_nodes_html("p.MSMRSTSignature_FullName.MSMRSTArticleItemTitle")
```

**Comment by kmike** [comment]
It is possible to develop a set of such reusable functions and use them without sending each time in the request; see http://splash.readthedocs.org/en/latest/scripting-tutorial.html#custom-lua-modules.

**Comment by kmike** [comment]
You can also use existing JS libraries to make data extraction easier, for example you can enable https://github.com/n1k0/casperjs/blob/master/modules/clientutils.js using [splash:autoload](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-autoload).
