### ISSUE TITLE
[QUESTION]wisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060:

### ISSUE THREAD

**Issue by JayVae** [scrapy-plugins/scrapy-splash#170]
HI!
I am a new bird of scrapy-splash,I have some problems running the project which tells:wisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060!
I don't know how to tackle this problem, but it didn't occur if I do not use scrapy-splash~

SO, can you give me some advice to handle this problem? Thanks a lot.

**Comment by kmike** [comment]
Is Splash available?

**Comment by JayVae** [comment]
@kmike Thanks, I have solved this problem, it is beacause I set the wrong **SPLASH_URL**.
