### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by LucasGorgal** [scrapy-plugins/scrapy-splash#171]
Hello. I have an ARM computer (Raspberry Pi) and I can't seen to run it.
When I try: `sudo docker run -p 8050:8050 scrapinghub/splash`
I get: `standard_init_linux.go:190: exec user process caused "exec format error"`

Thank you so much

**Comment by LucasGorgal** [comment]
Can confirm Scrapy works on ARM, so the problem is splash

**Comment by kmike** [comment]
I don't know how hard is it to make Splash work on ARM; I have neither ARM hardware to check, nor a use case for this. So help is appreciated. I'm closing this issue in favor of https://github.com/scrapinghub/splash/issues/373.

**Comment by heilwood** [comment]
installed on arm archlinux. All packages was installed manually:

sudo pacman -S python-pyqt5
sudo pacman -S python-sip-pyqt5 pyqt5-common
sudo pacman -S qt5-webkit
sudo pacman -S xorg-server-xvfb
yaourt -S ttf-wqy-zenhei-ibx
sudo pip install splash
sudo pip install lupa

python -m splash.server --port 8050
