### ISSUE TITLE
can't work with session and cookie

### ISSUE THREAD

**Issue by NewUserHa** [scrapy-plugins/scrapy-splash#172]
win10 10586
python3.6.5rc1 64
scrapy 1.5.0
scrapy_splash 0.7.2
splash last docker image from cn mirror in centos.

start from `scrapy shell "http://<docker host>/render.html?url=..."`

I tried the lua script from `Session Handling` of the readme, but it nerver work.
`splash.args.cookies` says `'NoneType' object is not iterable`.
I tried response.headers in both `execute` endpoint and `render.html` endpoin and always is
```
{b'Content-Type': b'application/json',
 b'Date': b'Sat, 31 Mar 2018 22:52:51 GMT',
 b'Server': b'TwistedWeb/16.1.1'}
```
only.
I tried response.cookiejar in `render.json` endpoint but it return `None`.

---
btw, I'm using like
```
a = scrapy_splash.SplashRequest("...", session_id='1', magic_response=True)  # (already requested the site ...)
fetch(a)
```
,then DUPEFILTER will keep stucking cmd.

**Comment by rizel10** [comment]
Have you tried using lua_source on `/execute` or `/run` endpoints?

Provide more details on your `SplashRequest` and your Lua script please

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
