### ISSUE TITLE
Is it possible to inherit SplashTextResponse from HtmlResponse but not TextResponse

### ISSUE THREAD

**Issue by JosephDeepIntelli** [scrapy-plugins/scrapy-splash#178]
In order to naturally use of CrawlSpider, is it possible to change the super class of SplashTextResponse to HtmlResponse from TextResponse? Though HtmlResponse is just a naive wrapper of TextResponse, However, CrawlSpider use the type of response  as a condition for future processing in method ` _requests_to_follow`, it requires an instance of HtmlResponse but not TextResponse.

**Comment by Gallaecio** [comment]
May this be a duplicate of #114?
