### ISSUE TITLE
not work splash

### ISSUE THREAD

**Issue by 02wallo** [scrapy-plugins/scrapy-splash#18]
I used a splash in the url. However, that did not work.

``` py
    def parse(self, response):
        url = 'http://www.gymboree.com/shop/dept_item.jsp?PRODUCT%3C%3Eprd_id=845524446071240&FOLDER%3C%3Efolder_id=2534374306289499&ASSORTMENT%3C%3East_id=1408474395917465&bmUID=kQCLfxQ&productSizeSelected=0&fit_type='
        yield scrapy.Request(url, self.parse_link, meta={
                'splash': {
                    'args': {'png': 1},
                }
            })


    def parse_link(self, response):
        body = json.loads(response.body)
        print body['url']
        import base64
        png_bytes = base64.b64decode(body['png'])
        with open('result.png', 'wb') as f:
            f.write(png_bytes)
```

But it was applied directly to the browser.

http://192.168.59.103:8050/render.png?url=http://www.gymboree.com/shop/dept_item.jsp?PRODUCT%3C%3Eprd_id=845524446070955&FOLDER%3C%3Efolder_id=2534374305284899&ASSORTMENT%3C%3East_id=1408474395917465&bmUID=kQD1brH&productSizeSelected=0&fit_type=

It was working.
And I found that that works by using the url obtained by using the Google URL Shortener.

I do not know why that should work when using the original url. I would like to know the solutions. Please help me.

**Comment by vionemc** [comment]
I get the same issue with every JSP based site.

**Comment by Gallaecio** [comment]
Is that your actual code? Because you don’t seem to be using `SplashRequest` at all.
