### ISSUE TITLE
JavaScript? Nope! Doesn't execute document.location.reload();

### ISSUE THREAD

**Issue by asix1337** [scrapy-plugins/scrapy-splash#183]
After 20 or more crawls, the website return following response:

Raw: https://pastebin.com/W8JVAkEe
Formated: https://pastebin.com/kBhbjUr3

A normal Browser execute the javascript and reload the pages sometimes. Splash doesnt execute the response, so i cant select anything. A browser returns after some reloads the correct content.

**Comment by Gallaecio** [comment]
Can you still reproduce this issue? Can you share the corresponding URL? Can you reproduce this issue using Splash directly, instead of using scrapy-splash?
