### ISSUE TITLE
How to handle Python Scrapy Splash error 502 due to auto-launch download

### ISSUE THREAD

**Issue by VishalSharmavj** [scrapy-plugins/scrapy-splash#184]
I'm using the code:

```
def start_requests(self):


        yield SplashRequest("https://www.example.com/myfilelinkextract/", callback=self.parse)
    def parse(self, response):
        # y = response.xpath('//*[@id="download_sub_text"]').extract()
        # print(y)
        print(response.body)
```

so that I can extract the download link of a file present in a onclick js like -
```
<div id="download_div" class="row" style="margin-left: 2%; margin-right: 2%">
<p id="download_sub_text" class="hide-on-small-only" style="text-align: center;">
    You could also download directly by
    <a onclick="ga('send', 'event', 'link', 'click_here', 'wholesale.item');"
        href="http://example.com/f2c9bd13afd7a17af35ad30a2c593c7f4bea2dd347b4149">
        clicking here!
    </a>
```
but i'm getting the following Debug.

```

2018-07-31 04:26:14 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying
 <GET https://www.example.com/myfilelinkextract/ via http://localhost:8050/render.html> (failed 3 times): 502 Ba
d Gateway
2018-07-31 04:26:14 [scrapy.core.engine] DEBUG: Crawled (502) <GET https://www.example.com/myfilelinkextract/ vi
a http://localhost:8050/render.html> (referer: None)
b'{"info": {"code": 102, "url": "https://www.example.com/myfilelinkextracted_link_which_I_want", "type": "WebKit", "text": "Frame load interrupted by policy change"}, "error": 502, "type": "RenderError", "description": "Error rendering page"}
```

It must be noted that except the pages which triggers the download, the code is working fine and I'm able to extract response.body without an issue.

Also, is there a way that I can extract/yield the dictionary I got in the Debug bcz it will do the work for me.

``b'{"info": {"code": 102, "url": "https://www.example.com/myfilelinkextracted_link_which_I_want", "type": "WebKit", "text": "Frame load interrupted by policy change"}, "error": 502, "type": "RenderError", "description": "Error rendering page"}'`
`
because what I want is just the url "https://www.example.com/myfilelinkextracted_link_which_I_want" which is same as present in onclick and also which gets auto-triggered for download.

**Comment by Gallaecio** [comment]
Does this still happen to you?
