### ISSUE TITLE
set multi SPLASH_URLS

### ISSUE THREAD

**Issue by wisew** [scrapy-plugins/scrapy-splash#185]
I have multiple servers,so I want to implement dynamic urls.What should I do?

**Comment by lopuhin** [comment]
@wisew you can specify ``splash_url`` argument for the ``SplashRequest``: https://github.com/scrapy-plugins/scrapy-splash#requests or alternatively use https://github.com/TeamHG-Memex/aquarium to run a pool of splash processes under one proxy

**Comment by wisew** [comment]
@lopuhin Thanks,I have soloved the problem by specifing splash_url argument for the SplashRequest.

**Comment by Gallaecio** [comment]
@wisew Can you close this issue?
