### ISSUE TITLE
"Thai" Language error

### ISSUE THREAD

**Issue by tarekbadrsh** [scrapy-plugins/scrapy-splash#186]
I tried to take screen shot of this tweet
"https://twitter.com/nanamaboy/status/1030380062300823552"
and got error in rendering "Thai" text
![1030380062300823552](https://user-images.githubusercontent.com/31471186/44425224-88dca980-a58b-11e8-80e7-73c2913bb1a3.png)

note: screen shot works with me very well with all language , except "Thai".

**Comment by Gallaecio** [comment]
Does it work when you use Splash directly instead of using scrapy-splash?
