### ISSUE TITLE
! within url leading to not understood url

### ISSUE THREAD

**Issue by gandalfb** [scrapy-plugins/scrapy-splash#19]
Hi and thanks for the great work.
I am currently experimenting with splash and scrapyjs and stumbled upon a behavior.

If I call from scrapy:8050 (start page) a url with "!" it renders without problem. The url arg is being properly escaped.
If I call it from scrapyjs the "!" leads to a "_escaped_fragment_=" in the request.body, being not correctly escaped by scrapyjs, it seems.

P.S.: Source was pip install scrapyjs

**Comment by kmike** [comment]
Scrapy escapes URL fragments using AJAX escaping scheme. If you want to pass a URL with a fragment to Splash then set url in args dict manually:

``` py
url = 'http://example.com#id2'
yield scrapy.Request(url, meta={
    'splash': {'args': {'url': url}}
})
```

I've documented it here: https://github.com/scrapy-plugins/scrapy-splash/commit/df63383a8fe96fb521e1d9035785d01d53d825d5. Sorry for the confusion.
