### ISSUE TITLE
scrapy-splash with proxy

### ISSUE THREAD

**Issue by voanhq** [scrapy-plugins/scrapy-splash#190]
Hello fellow scrapers. I am writing a spider to check if the proxy lua script works by printing the text from "http://httpbin.org/ip".

The spider is ran through splash with docker.

My list.txt file (where the proxies are located ) are written in the following format:
208.38.227.219:36354
51.68.162.103:5836
41.170.14.26:43370
78.26.154.73:58207
...
...

My spider is as follows: 
    import scrapy
    from scrapy_splash import SplashRequest
    import random

    class ProxySpider(scrapy.Spider):
        name = 'check'
        f = open("D:/project/random-proxy/list.txt","r")
        l = []
        for i in f:
        l.append(i)
        line = [i.replace('\n','') for i in l]
        proxy = random.choice(line)
        proxy_addr = "http://" + str(proxy)

        lua_script = """
            function main(splash, args)
            assert(splash:go{splash.args.url,http_method=splash.args.http_method,body=splash.args.body})
            assert(splash:wait(0.5))
            splash:on_request(function(request)
                request:set_proxy{host = "http://%s", port = %s}
            end)
            return splash:html()
            end
            """ % (proxy.split(':')[0],proxy.split(':')[1])

        def start_requests(self):
            yield SplashRequest(url='http://httpbin.org/ip',callback=self.parse,endpoint='execute',
                args={'lua_source': self.lua_script,'proxy':self.proxy_addr})
     
        def parse(self, response):
            yield{'Text':response.text}

And the output:

    2018-09-27 13:14:32 [scrapy_splash.middleware] WARNING: Bad request to Splash: {'type': 
    'ScriptError', 
    'description': 'Error happened while executing Lua script', 'info': {'line_number': 3, 'type': 'LUA_ERROR', 
    'error': 'network1', 'message': 'Lua error: [string "..."]:3: network1', 'source': '[string "..."]'}, 'error': 400}
    2018-09-27 13:14:32 [scrapy.core.engine] DEBUG: Crawled (400) <GET http://httpbin.org/ip via 
    http://10.0.75.1:8050/execute> (referer: None)
    2018-09-27 13:14:32 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <400 
    http://httpbin.org/ip>: HTTP status code is not handled or not allowed
    2018-09-27 13:14:32 [scrapy.core.engine] INFO: Closing spider (finished)

Please advise me on what the problems is. As I am relatively new to scraping, I hope you can provide me with answers that are easy to understand. Many thanks

**Comment by ghost** [comment]
@voanhq how did you solve this problem?
