### ISSUE TITLE
Scraping is blocked

### ISSUE THREAD

**Issue by eliavm** [scrapy-plugins/scrapy-splash#195]
When trying to scrape a page I'm getting empty page with one div `<div id="distilIdentificationBlock"> </div>`

Found something on stackoverflow that might be relevant: https://stackoverflow.com/questions/45060011/crawling-web-using-selenium-chrome-driver-but-still-blocked 

Any idea how to bypass this?

Using Scrapy 1.5.1 + scrapy-splash 0.7.2

**Comment by al-serebrov** [comment]
Hi @eliavm !
Unfortunately, you are hitting the website using Distil Antibot measures, and there's no "silver bullet" to propose you. 
There are some solutions and thoughts available on this topic, e.g. [here](https://www.reddit.com/r/webdev/comments/5q1ypx/what_is_your_approach_on_scraping_distil_networks/) and [here](https://www.blackhatworld.com/seo/python-scraping-distil-protected-sites.988967/), but generally you need to use proxies and develop some browser fingerprinting into your spider (pretend that you are an actual human being) - all of these things are pretty complicated and not really related to the Splash itself, as you can face the same responses using other headless browsers (e.g. Selenium).

**Comment by JavierRuano** [comment]
I have "read" about here.

Another resource,
https://www.blackhatworld.com/seo/python-scraping-distil-protected-sites.988967/

i don't know if it is useful, sorry.
i don't speak chinese.
https://www.jianshu.com/p/be856bc15afb

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Gallaecio** [comment]
@eliavm Could you close this issue, as it is not really about scrapy-splash?
