### ISSUE TITLE
Filters - not working? 

### ISSUE THREAD

**Issue by harrisonhparker1994** [scrapy-plugins/scrapy-splash#197]
Hi Mikhail, 

I sent you an email, but I thought I'd detail out the issue here.  Basically it doesn't seem like filters work for dockerized splash.  

I basically followed the example on the main splash page about blocking [fonts ](https://splash.readthedocs.io/en/stable/api.html#request-filters).  I made the same file in the correct location.  Indeed, when splash starts up, it prints out that it is reading all the filter txt files.  

However, I paste an html render link (will paste below) into firefox after clearing all my cache and the fonts are not blocked at all!  Is this a bug? 

This is what my nofont filter looks like (I've tried many other adblock syntaxes, none work) 

```
.ttf|
.woff|
```
Here is the link I put into my firefox: 

http://<ip_of_splash>:8050/render.html?url=https://www.cnn.com&timeout=60&wait=5&image=0&filters=nofont

And here's what I see when I load it in firefox: 

![image](https://user-images.githubusercontent.com/43893703/48666428-b2b44800-ea76-11e8-8eb9-4d684146f478.png)

It seems like the fonts still make it through.  I'd like to use the adblock filters to remove all images, CSS, fonts, etc.  Bascially all the fat except the text of the pages. 

Let me know what you think!

**Comment by Gallaecio** [comment]
Your filter says `woff`, but the file extensions of the files from the screenshot look like `woff2`. Might that be the reason?
