### ISSUE TITLE
crawlera integration in scrapy splash

### ISSUE THREAD

**Issue by spokharel41** [scrapy-plugins/scrapy-splash#200]
![error](https://user-images.githubusercontent.com/12790944/48981233-0d931280-f0fb-11e8-8c92-f6e72634b767.png)
I'm getting this error while integrating scrapy splash with crawlera.
My spider code is :
yield SplashRequest(url = final_url, callback = self.parse, endpoint = 'render.html', splash_headers = {'Authorization':basic_auth_header(self.settings['my splash api key'], ''),}, args = {'lua_source':self.LUA_SOURCE, 'crawlera_user':self.settings['my crawlera api key'],}, cache_args = {'lua_source'}, meta = {'some_value': some_value})

scripts/crawlera.lua , settings and setup.py are similar as the official docs.

**Comment by lopuhin** [comment]
@spokharel41 looks like currently ``dict_hash`` function does not support ``None`` values, I don't see any reason why it shouldn't support them, looks like a bug to me, sorry about that.
If you would like to work around it, I suggest checking if any value you pass to ``SplashRequest`` is None, and omitting it (or making it non-None).

**Comment by spokharel41** [comment]
@lopuhin Thanks. This solved the issue of yield SplashRequest. However, now i'm getting 
{"error": 400, "info": {"description": "Required argument is missing: lua_source", "argument": "lua_source", "type": "argument_required"}, "description": "Incorrect HTTP API arguments", "type": "BadOption"}
on https://splash-instance-url/execute
My splashrequest is:
yield SplashRequest(url = final_url, callback= self.parse, endpoint = 'execute', splash_headers = {'Authorization': basic_auth_header(self.settings['SPLASH_APIKEY'],''),}, args = {'lua_source' : self.LUA_SOURCE, 'crawlera_user' : self.settings['CRAWLERA_APIKEY'],}, cache_args = ['lua_source'])
this is my crawlera.lua file:
function use_crawlera(splash)
    local user = splash.args.crawlera_user
    local host = 'proxy.crawlera.com'
    local port = 8010
    local session_header = 'X-Crawlera-Session'
    local session_id = 'create'

    splash:on_request(function (request)
        request:set_header('X-Crawlera-Cookies', 'disable')
        request:set_header(session_header, session_id)
        request:set_proxy{host, port, username=user, password=''}
    end)

    splash:on_response_headers(function (response)
        if response.headers[session_header] ~= nil then
            session_id = response.headers[session_header]
        end
    end)
end

function main(splash)
    use_crawlera(splash)
    splash:go(splash.args.url)
    return splash:html()
end

**Comment by lopuhin** [comment]
@spokharel41 it says that ``lua_source`` is required, could you please verify that you are passing it and check itss value?

**Comment by spokharel41** [comment]
@lopuhin yes. before the yield splashrequest if i print self.LUA_SOURCE then it prints the crawlera.lua file contents.

**Comment by spokharel41** [comment]
def __init__(self, *args, **kwargs):
                self.LUA_SOURCE = get_data('myproject','scripts/crawlera.lua').decode('utf-8')
		super(mySpider, self).__init__(*args, **kwargs)
This function is in my spider before the start_requests function.

**Comment by Gallaecio** [comment]
@spokharel41 Did you ever manage to fix this issue?

**Comment by spokharel41** [comment]
No. I didn't. I moved forward by another approach.

**Comment by ghost** [comment]
@spokharel41 what approach did you use?
