### ISSUE TITLE
Third party plugin used in website are not run

### ISSUE THREAD

**Issue by bikashburma615** [scrapy-plugins/scrapy-splash#203]
Example: 

let take a site:

https://www.chubbiesshorts.com/products/the-arnolds

if inspect the website, and search for "yotpo-main-widget" class, the dynamic html content generated by this yotpo is not not rendered. Can any one help me?

**Comment by bikashburma615** [comment]
Is this a invalid issue??? Can anyone help me please?

**Comment by lopuhin** [comment]
@bikash615 please check out some possible solutions to the issue that website is not rendered correctly: https://splash.readthedocs.io/en/stable/faq.html#website-is-not-rendered-correctly

**Comment by bikashburma615** [comment]
@lopuhin i went through this page, i tried everything, but none of them is working. Can you please help me, its really urgent.

**Comment by bikashburma615** [comment]
import scrapy
from scrapy_splash import SplashRequest

class MySpider(scrapy.Spider):
    name = 'yotpo-scrapper'

    allowed_domains = ['www.everlast.com']
    start_urls = ['https://www.everlast.com/fight/boxing/gloves/1910-classic-fight-gloves']
    script1 = """

    function main(splash)
      splash.js_enabled = true
      splash.plugins_enabled = true
      splash.indexeddb_enabled = true
      splash.html5_media_enabled = true
      splash:set_viewport_full()
      splash:init_cookies(splash.args.cookies)
      splash:set_user_agent(splash.args.ua)
      assert(splash:go(splash.args.url))
      
      splash:wait(5)
    
      splash:runjs("document.querySelector('.yotpo-nav-tab .yotpo-active').click()")
      splash:wait(5)
      
      return {cookies = splash:get_cookies(), html=splash:html()}
    end
    """

    def start_requests(self):
        for url in self.start_urls:
            yield SplashRequest(url, self.parse, endpoint='execute',
                                args={'lua_source': self.script1,
                                      'ua': "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"})

    def parse(self, response):
        print("final respose", response.body)
        yield

**Comment by bikashburma615** [comment]
This is my code, trying all the way, but the dynamic html content is still not being rendered... A small help will really be appreciated

**Comment by lopuhin** [comment]
@bikash615 thanks for providing the code. It looks good. As the next step in debugging it, I would suggest to get the HAR output from splash and from the browser, and try to see if any requests are not happening for some reason. To view HAR you can use either Splash UI, or Chrome dev tools.

**Comment by bikashburma615** [comment]
widget.js script is not being executed in splash UI, may be that is the reason, can i trigger it manually?

**Comment by Gallaecio** [comment]
@bikash615 Did you even manage to solve your issue?
