### ISSUE TITLE
How to send new request on rendered page after splashrequest?

### ISSUE THREAD

**Issue by justinleeone** [scrapy-plugins/scrapy-splash#204]
HI,
I have spider project, need input username and password. after that I must wait verification code from e-mail to finish login.
In this  case,  I input login's information through splashrequest first time.When I get verification code, send code through splashrequest second. However, response is not login page.
So, have any way to go back login page that first time splashrequest? I mean that I want to find fist time splashrequest's rendered page, and then I can send new js code.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.
