### ISSUE TITLE
Unable to run the container in Azure Web App Service

### ISSUE THREAD

**Issue by sadiq-mc** [scrapy-plugins/scrapy-splash#206]
I tried to run the Splash container in Azure Web App service by pulling from Docker Hub. Unfortunately, the app was not starting. Below is the log from the Azure service,

> 2019-02-07 04:58:35.812 INFO  - Issuing docker pull: imagename =scrapinghub/splash:latest
2019-02-07 04:58:35.949 INFO  - Issuing docker pull: imagename =scrapinghub/splash:latest
2019-02-07 04:58:36.063 INFO  - Issuing docker pull scrapinghub/splash:latest
2019-02-07 04:59:25.695 INFO  - docker pull returned STDOUT>> latest: Pulling from scrapinghub/splash
7b722c1070cd: Pulling fs layer
5fbf74db61f1: Pulling fs layer
ed41cb72e5c9: Pulling fs layer
7ea47a67709e: Pulling fs layer
e352f2e1f6cd: Pulling fs layer
b995bfaabf1d: Pulling fs layer
1ed340027368: Pulling fs layer
386db981613e: Pulling fs layer
e2e4f0e521c0: Pulling fs layer
b995bfaabf1d: Verifying Checksum
b995bfaabf1d: Download complete
7ea47a67709e: Verifying Checksum
7ea47a67709e: Download complete
5fbf74db61f1: Verifying Checksum
5fbf74db61f1: Download complete
ed41cb72e5c9: Verifying Checksum
ed41cb72e5c9: Download complete
e352f2e1f6cd: Verifying Checksum
e352f2e1f6cd: Download complete
e2e4f0e521c0: Verifying Checksum
e2e4f0e521c0: Download complete
7b722c1070cd: Verifying Checksum
7b722c1070cd: Download complete
7b722c1070cd: Pull complete
5fbf74db61f1: Pull complete
ed41cb72e5c9: Pull complete
386db981613e: Verifying Checksum
386db981613e: Download complete
7ea47a67709e: Pull complete
1ed340027368: Verifying Checksum
1ed340027368: Download complete
e352f2e1f6cd: Pull complete
b995bfaabf1d: Pull complete
  
> 2019-02-07 04:59:25.696 ERROR - docker pull returned STDERR>> failed to register layer: Error processing tar file(exit status 1): Container ID 834600147 cannot be mapped to a host ID

> 2019-02-07 04:59:25.698 INFO  - Starting container for site
2019-02-07 04:59:25.699 INFO  - docker run -d -p 47498:8050 --name mc-splash_0 -e PORT=8050 -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=mc-splash -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_INSTANCE_ID=d0fd332e2e657cc5a5784e0cd0ebc3d6a210cb33ba151113cbc811b1e894878 -e HTTP_LOGGING_ENABLED=1 scrapinghub/splash:latest  

> 2019-02-07 04:59:25.833 ERROR - Container create failed for mc-splash_0 with System.AggregateException, One or more errors occurred.
InnerException: Docker.DotNet.DockerContainerNotFoundException, Docker API responded with status code=NotFound, response={"message":"No such image: scrapinghub/splash:latest"}

Any help is appreciated.

**Comment by Gallaecio** [comment]
@sadiq-mc Did you ever manage to solve your issue?

**Comment by sadiq-mc** [comment]
@Gallaecio Sorry for the delayed response. I didn't able to resolve this issue yet.

**Comment by Chryogenic** [comment]
I get the same error. Is there any other way to host it in azure?

**Comment by Gallaecio** [comment]
This looks like an issue with the Splash docker image, rather than with `scrapy-splash`. Could you please report this on https://github.com/scrapinghub/splash?

Please, mention https://circleci.com/docs/2.0/high-uid-error/ which seems to explain the root of the error and how to solve it (as in how Splash developers can fix the issue).
