### ISSUE TITLE
Lua script failed clicking on a button

### ISSUE THREAD

**Issue by elados93** [scrapy-plugins/scrapy-splash#207]
I'm trying to scrape flights from [link](http://www.iaa.gov.il/en-us/airports/BenGurion/Pages/OnlineFlights.aspx) with scrapy-splash using this lua script:

```
function main(splash)
                local waiting_time = 2 

                -- Go to the URL
                assert(splash:go(splash.args.url))
                splash:wait(waiting_time)

                -- Click on "Outgoing tab"
                local outgoing_tab = splash:select('#linkRealTimeOutgoing')
                outgoing_tab:mouse_click()
                splash:wait(waiting_time)

                -- Click on "More Flights" button
                local more_flights_btn = splash:select('#ctl00_rptOutgoingFlights_ctl26_divPaging > div.advanced.noTop > a')
                more_flights_btn:mouse_click()
                splash:wait(waiting_time)

                return splash:html()
end
```
and from some reason I'm getting this error:

`'LUA_ERROR', 'message': 'Lua error: [string "..."]:16: attempt to index local \'more_flights_btn\' (a nil value)', 'error': "attempt to index local 'more_flights_btn' (a nil value)"}, 'type': 'ScriptError', 'description': 'Error happened while executing Lua script'}`
Does anyone know why this happens? Also does anyone know where I can get a toturial for lua script integration with splash? besides the offical site?

Thanks in advance!

**Comment by JavierRuano** [comment]
Because the button doesn't exist still. You should wait for the button.

**Comment by elados93** [comment]
Thank you for your answer @JavierRuano 
I changed to this code:
```
function main(splash)
                    
                    function click_on(label)
                        for i=1,10 do
                        splash:wait(1)
                        btn = splash:select(label)
                        if btn then break end
                        end
                        btn:mouse_click()
                    end
                    
                    local waiting_time = 2 
                              
                    -- Go to the URL
                    assert(splash:go(splash.args.url))
                    splash:wait(waiting_time)
                    
                    -- Click on "Outgoing tab"
                    click_on('#linkRealTimeOutgoing')

                    -- Click on "More Flights" button
                    click_on('#ctl00_rptOutgoingFlights_ctl26_divPaging > div.advanced.noTop > a')
                    splash:wait(waiting_time)

                    return splash:html()
 end
```
and still getting this error for nil element, I also tried while loop with condition (element == nil) and it doesn't help. any ideas? maybe something here is Async and need to make it sync?

Thanks

**Comment by JavierRuano** [comment]
That book is cool, but i think lua consumes a lot of memory more than
another options. it exists error of limit memory too (splash)

Programming in Lua
<https://www.amazon.com/exec/obidos/ASIN/8590379868/lua-pilindex-20>by
Roberto Ierusalimschy

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.

**Comment by elados93** [comment]
SOLVED! I should re-load the URL when it got stuck

**Comment by zqxyus** [comment]
How to re-reload the URL? to use  splash:go(splash:url())?
