### ISSUE TITLE
How to maintain session in scrapy-splash request 

### ISSUE THREAD

**Issue by Durai4024** [scrapy-plugins/scrapy-splash#208]
I am using scrapy-splash for website where  JavaScript is rendering properly.I want to click next page button to navigate and button click is working fine it is going 2nd page.But the problem here is when I do callback It is loading first page of the website.So I am not able to navigate 3rd,4th...further page. Please suggest the solution to handle this

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.
