### ISSUE TITLE
Live Webkit window OSX

### ISSUE THREAD

**Issue by ddofborg** [scrapy-plugins/scrapy-splash#209]
I was not able to get this running on OSX using the command on https://splash.readthedocs.io/en/stable/kernel.html#live-webkit-window Maybe they are different on OSX (and I have tried some other from the Internet), but it never worked.

Is there anyone who has this working? I would be great to be able to interact with Splash while it's running.

**Comment by Gallaecio** [comment]
Could you please close this issue and report it on https://github.com/scrapinghub/splash?
