### ISSUE TITLE
Can not connect to splash url

### ISSUE THREAD

**Issue by cyclehacker** [scrapy-plugins/scrapy-splash#21]
The SPLASH_URL = 'http://192.168.59.103:8050' provided does not connect, I get the following error:

DEBUG: Gave up retrying <POST http://192.168.59.103:8050/render.html> (failed 3 times): TCP connection timed out: 110: Connection timed out.

I can use the following command to run Splash in my browser:

$ sudo docker run -p 5023:5023 -p 8050:8050 -p 8051:8051 scrapinghub/splash

Which makes Splash available at: 0.0.0.0 at ports 8050 (http), 8051 (https) and 5023 (telnet). However, I can not then use the terminal to run my Scrapy spider. 

I'm running Ubuntu 14.04.

Any help you can provide to get me up and running would be much appreciated.

**Comment by kmike** [comment]
SPLASH_URL = 'http://192.168.59.103:8050'  is just an example, you should put an address of your Splash instance to this option (0.0.0.0:8050 in your case).
