### ISSUE TITLE
Restrict acess by username and password

### ISSUE THREAD

**Issue by ChristophKind** [scrapy-plugins/scrapy-splash#210]
Is it possible to set a username and a password for the http api?

**Comment by lopuhin** [comment]
@ChristophKind this is not available in Splash, but you can use https://github.com/TeamHG-Memex/aquarium for that

**Comment by Gallaecio** [comment]
This is covered at https://splash.readthedocs.io/en/stable/faq.html#how-to-run-splash-in-production
