### ISSUE TITLE
Problems rendering embedded videos

### ISSUE THREAD

**Issue by alleycat08** [scrapy-plugins/scrapy-splash#218]
Hello,

I've been having difficulties capturing screenshots of sites like Twitter. When I try, I get screenshots that have boxes that say "We cannot play the video in this browser. Please try a different web browser." - see attached image. I've tried playing with enabling plugins, html5, and changing the user agent, to no success.

Additionally, when encountering embedded videos elsewhere, such as NYT, a similar problem arises where there's an empty box where there should be an embedded video.

Any help is appreciated

![error](https://user-images.githubusercontent.com/49795579/56442032-26c07980-62bd-11e9-88df-07fe0d4c7c10.png)

**Comment by Gallaecio** [comment]
@alleycat08 Is it possible that you meant to create an issue for [Splash](https://github.com/scrapinghub/splash), and not for scrapy-splash (which simply offers integration between Splash and Scrapy)? Or does this happen only when using scrapy-splash, and not when using Splash directly?

Also, have you checked [Splash’s FAQ section about website rendering issues](https://splash.readthedocs.io/en/stable/faq.html#website-is-not-rendered-correctly)?
