### ISSUE TITLE
Rename to scrapy-splash?

### ISSUE THREAD

**Issue by pablohoffman** [scrapy-plugins/scrapy-splash#22]
What do you think about renaming this project to `scrapy-splash` to follow the standard naming convention of [scrapy plugins](https://github.com/scrapy-plugins)?

In the past, we had another `scrapy-splash` repository (that could conflict with this) but that is now gone and removed for good.

**Comment by dangra** [comment]
+1 to `scrapy-splash` but may be `scrapy-javascript` if we ever plan to have other backends

**Comment by pablohoffman** [comment]
@kmike will correct me if I'm wrong but I don't think supporting other backends was ever the goal of this package.

**Comment by kmike** [comment]
I'm fine with it.

**Comment by dangra** [comment]
I renamed the github repo. hey! it is a start :golf:

**Comment by kmike** [comment]
Fixed!
