### ISSUE TITLE
Only get popup message content as response

### ISSUE THREAD

**Issue by kadenn** [scrapy-plugins/scrapy-splash#220]
Website Im trying to scrape: https://uk.tommy.com/flat-logo-espadrilles-fw0fw04007731

What should I to reach real content of website.

HTML response from splash: 
[uk.tommy.com.txt](https://github.com/scrapy-plugins/scrapy-splash/files/3115811/uk.tommy.com.txt)

![uk tommy com](https://user-images.githubusercontent.com/20323479/56717658-d9715b80-6745-11e9-9587-dbe95dd9c607.png)

**Comment by lopuhin** [comment]
@kadenn you can run a custom JS code that would close the popup (e.g. by clicking on the cross), or do the same via splash helpers, see https://splash.readthedocs.io/en/stable/scripting-overview.html#interacting-with-a-page for both approaches

**Comment by kadenn** [comment]
It worked, thank you @lopuhin
