### ISSUE TITLE
Run splash using docker compose with args like --max-timeout  --disable-lua-sandbox

### ISSUE THREAD

**Issue by largomath2010** [scrapy-plugins/scrapy-splash#221]
Hi, it's normal to run splash like:

docker run -p 8050:8050 scrapinghub/splash --max-timeout 3600 --disable-lua-sandbox

Now I move to docker-composer v3. How can i add those args like max-timeout, disable-lua-sandbox.

My current code that not working:

splash:
    image: scrapinghub/splash
    command: bash "splash --max-timeout 3600"

Thanks.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/splash-js-render) to ask this type of questions.
