### ISSUE TITLE
How to fix Lua error in scrapy_splash when running on docker?

### ISSUE THREAD

**Issue by Mageshwaran2314** [scrapy-plugins/scrapy-splash#224]
I set up docker image for scrapy splash and I test it with many urls, after some times I got an error when try the url (https://www.udemy.com/)

HTTP Error 400 (Bad Request)
Type: ScriptError -> LUA_ERROR
```

Error happened while executing Lua script

Lua error: [string "function main(splash, args) ..."]:2: http403


{
    "type": "ScriptError",
    "info": {
        "message": "Lua error: [string \"function main(splash, args)\r...\"]:2: http403",
        "type": "LUA_ERROR",
        "source": "[string \"function main(splash, args)\r...\"]",
        "line_number": 2,
        "error": "http403"
    },
    "error": 400,
    "description": "Error happened while executing Lua script"
}
```

**Comment by Gallaecio** [comment]
Could you share some [minimal code](https://stackoverflow.com/help/mcve) to reproduce the issue?

**Comment by Gallaecio** [comment]
It looks like you are getting a 403 response. This may be due to the website detecting unusual activity from your IP and choosing to disallow access. Could that be the case?

**Comment by Mageshwaran2314** [comment]
actually I don't use the lua code, I just render the web site in http://0.0.0.0:8050 from scrapy-splash docker image

**Comment by azmirfakkri** [comment]
How did you call your lua script? Did you point to a `.lua` file or putting the lua script as a string constant?
