### ISSUE TITLE
Why does SplashMiddleware expose my spider?

### ISSUE THREAD

**Issue by internalG** [scrapy-plugins/scrapy-splash#226]
I have a same project running on 2 machines. One has no firewall and all ports are available, the splash runs well. Another machine has the firewall, only 80 and 443 are available. The SplashRequest always returns 403 to abandon the crawl. I find I can comment out the scrapy_splash.SplashMiddleware option to get the crawl working. I want to know it's caused by SplashMiddleware or the docker behind the firewall?

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.
