### ISSUE TITLE
Cant get any response with Scrapy+Splash but with Pure Scrapy I get response

### ISSUE THREAD

**Issue by kadenn** [scrapy-plugins/scrapy-splash#229]
I tried "ROBOTSTXT_OBEY = False", increasing timeout and "http://localhost:8050" but didn't work with Scrapy+Splash. Then I tried Pure Scrapy Request with same code and same settings and It worked. Pure Scarpy isn't enough itself for me. I need your help to understand why splash doesn't work with that website and how to fix it. The website Im talking about: https://www.asos.com/

**Comment by rafikahmed** [comment]
Hi Kadenn, 
First of all you need to disable private mode in Splash and assign a valid user agent to the request.
Here is the code is used:

```
function main(splash, args)
  splash.private_mode_enabled = false
  headers = {
    ['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36'
  }
  splash:set_custom_headers(headers)
  assert(splash:go(args.url))
  assert(splash:wait(0.5))
  return splash:png()
end
```
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/41229637/60456449-2df6f280-9c31-11e9-9fa8-73af7daa570a.PNG">

I tested it and did work perfectly fine on my side. 
Make sure you return splash:html() instead of splash:png() so you can parse the response using Scrapy.
Kind regards,
Ahmed.

**Comment by kadenn** [comment]
> Hi Kadenn,
> First of all you need to disable private mode in Splash and assign a valid user agent to the request.
> Here is the code is used:
> 
> ```
> function main(splash, args)
>   splash.private_mode_enabled = false
>   headers = {
>     ['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36'
>   }
>   splash:set_custom_headers(headers)
>   assert(splash:go(args.url))
>   assert(splash:wait(0.5))
>   return splash:png()
> end
> ```
> 
> <img alt="Capture" width="960" src="https://user-images.githubusercontent.com/41229637/60456449-2df6f280-9c31-11e9-9fa8-73af7daa570a.PNG">
> 
> I tested it and did work perfectly fine on my side.
> Make sure you return splash:html() instead of splash:png() so you can parse the response using Scrapy.
> Kind regards,
> Ahmed.

First of all thank you for saving me from this trouble, It worked for me too. I was already chancing user agents  randomly and my private_mode set to FALSE while I was creating docker container. I don't understand why it is working when you set from script in spider but not working when I set from settings.py.
