### ISSUE TITLE
Support exit proxies

### ISSUE THREAD

**Issue by dvdbng** [scrapy-plugins/scrapy-splash#23]
At the moment you can use a proxy to connect to splash by setting the `proxy` property of `request.meta`, but there is no way to set the proxy splash will use for accessing the page.

Splash doesn't have a parameter to set the proxy yet (see https://github.com/scrapinghub/splash/issues/160 ) but if implemented this middleware should allow setting it somehow.

I propose that if proxy is set before scrapyjs middleware, scrapyjs uses that proxy as splash outgoing proxy and clear the `request.meta['proxy']` variable, if it's set after it means that the proxy will be used to connect to splash instead. Note that you can use a proxy to connect to splash and a proxy to connect to the page by setting the same property twice in different middlewares (confusing... and at the same intuitive).

We would, of course, also still support `request.meta[splash][args][proxy]` and `request.meta[splash][args][proxy_url]` if added, and rise an exception if different options are set and differ.

As an alternative, we could support only `request.meta[splash][args][proxy_url]`, but it would make it incompatible with other middlewares that might set the proxy and are not scrapyjs-aware. This would not require changes to scrapyjs, just to implement that parameter in splash.

**Comment by kmike** [comment]
Passing proxy to http://splash.readthedocs.org/en/stable/api.html#arg-proxy by default makes sense to me, +1 to do that. 

I think we shouldn't touch `request.meta['proxy']` if user set `request.meta['splash']['args']['proxy']` explicitly.

**Comment by eusid** [comment]
So does passing a proxy through splash args work or no ? I can't seem to get it to work this way.

**Comment by kmike** [comment]
@eusid it works, just like passing any other args. Do you have an example?

**Comment by Gallaecio** [comment]
@eusid Did you ever succeed using a proxy with Splash?
