### ISSUE TITLE
SplashRequest does not execute LUA script

### ISSUE THREAD

**Issue by sgalich** [scrapy-plugins/scrapy-splash#232]
In Splash browser my lua script works fine. It must be executed in several seconds due to the some "splash:wait(1)" lines. But SplachRequest yields response with url's html.text as soon as starts.

Here is my code:

```
def parse(self, response):
		<...>
    script ='''
function main(splash)
splash.resource_timeout = 10.0
assert(splash:go(splash.args.url))
splash:wait(2)
local element = splash:select('a.phone-trigger')
local bounds = element:bounds()
element:mouse_click{x=bounds.width/2, y=bounds.height/2}
splash:wait(2)
return splash:html()
end
'''
    args = {'lua_source': script,
		'timeout': 10,
		'resource_timeout': 10,
		'wait': 5,
		'har': 1,
		'html': 1,
		}
    yield SplashRequest(url=buyers_link,
			callback=self.parse_buyer,
			cb_kwargs=data,
			endpoint='execute',
			args=args,
			dont_filter = True
			)
def parse_buyer(self, response,
	                Title,
			Name,
	                Contact,
	                Region
	                ):
<...>
```

And no matters what is it in lua script, SplashRequest always does the same. Even if I write:
`script = """bla-bla-bla"""`
I did everything exectly with documentation: run Docker, install all required packages, make these project settings:
```SPLASH_URL = 'http://localhost:8050'
DOWNLOADER_MIDDLEWARES = {
                        'scrapy_splash.SplashCookiesMiddleware': 723,
                        'scrapy_splash.SplashMiddleware': 725,
                        'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 810
                       }
SPIDER_MIDDLEWARES = {
                        'scrapy_splash.SplashDeduplicateArgsMiddleware': 100
                    }
DUPEFILTER_CLASS = 'scrapy_splash.SplashAwareDupeFilter'
HTTPCACHE_STORAGE = 'scrapy_splash.SplashAwareFSCacheStorage'
```

But it works like there is no splash at all! Please, help me in solving this problem!

**Comment by azmirfakkri** [comment]
I have a similar issue where Splash cannot find my lua script.
I've tried putting my lua script as a string constant and another option is to point it to a separate lua file, both returns the same error.
All my settings and request looks correct and this code was running fine last time.

**Comment by SVGalich** [comment]
How do you run scrapy? By bash command “scrapy crawl...” or by CrawlProcess()?

**Comment by sgalich** [comment]
> I have a similar issue where Splash cannot find my lua script.
> I've tried putting my lua script as a string constant and another option is to point it to a separate lua file, both returns the same error.
> All my settings and request looks correct and this code was running fine last time.

How do you run scrapy? By bash command “scrapy crawl...” or by CrawlProcess().crawl(...)?

**Comment by sgalich** [comment]
A problem was in scrapy: when it runs via CrawlerProcess it does not load settings with splash middlewares from settings file.

**Comment by pearsonhenri** [comment]
Any more details on this issue? Not sure how this was resolved but I think I'm running into a similar issue here.

**Comment by sgalich** [comment]
> Any more details on this issue? Not sure how this was resolved but I think I'm running into a similar issue here.

How do you run your spider? Via  bash command “scrapy crawl...” or by CrawlProcess().crawl(...)?

**Comment by pearsonhenri** [comment]
Ah you know what, I actually think I figured it out (commented over [here](https://github.com/scrapy-plugins/scrapy-splash/issues/259#issuecomment-720536850)) but:
>setting the endpoint argument of your SplashRequest to execute (instead of the default render.html)

is what fixed me up. 

Is that the expected behavior? If so I'd be happy to throw in a little note in the README making that a bit more explicit :)
