### ISSUE TITLE
Splash with Tor

### ISSUE THREAD

**Issue by turangojayev** [scrapy-plugins/scrapy-splash#234]
I am creating a new issue, since the ones I have seen that were related, did not solve my problem. I have the following scenario: I have a docker image that is built on top of [https://github.com/dperson/torproxy](https://github.com/dperson/torproxy) and inside I have spiders for different domains (Tor and crawler project share the same docker image). I use the image above for the reason that I change IP address every N requests. Now the first time I need to scrape some data from a domain, where main things that I am interested in, require rendering javascript and after some googling I ended up being here. I am able to use splash with scrapy without Tor, however when I want to combine those two, I keep getting  

`2019-07-31 20:37:55 [scrapy.core.scraper] ERROR: Error downloading <GET SOME_URL via http://splash:8050/execute>`
`Traceback (most recent call last):`
`File "/usr/local/lib/python3.5/dist-packages/scrapy/core/downloader/middleware.py", line 44, in process_request`
`    defer.returnValue((yield download_func(request=request, spider=spider)))`
`twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
`

My docker-compose.yml looks like this:
<pre><code>
version: '2'
services:
  scraper:
    restart: always
    build: .
    container_name: scraper
    ports:
      - 8118:8118
      - 9050:9050
      - 9051:9051
    volumes:
      - /home/user/data:/data
    environment:
      - DATA_DIR=/data
  splash:
    image: scrapinghub/splash
    container_name: splash
    links:
      - scraper
    ports:
      - 8050:8050
</code></pre>

and my Lua script looks like this:
<pre><code>function main(splash)
    splash:on_request(function(request)
         request:set_proxy{ host = "scraper", port = 9050, type='socks' }
    end)
    splash:go('SOME_URL')
    splash:wait(0.5)
    local elements = splash:select_all('#Decisions > tbody > tr[style="cursor: pointer;"]')
    for _, el in ipairs(elements) do
       el:click()
       splash:wait(0.3)
    end
    return {splash:html()}
end
</code></pre>

When I log into scraper container with docker exec and try to use splash with curl, it works. Also when I log into splash container and try to use Tor proxy running on scraper container with `curl -s --socks5-hostname scraper:9050 SOME_OTHER_URL` things seem to be working. Any ideas what could be the problem?

**Comment by Gallaecio** [comment]
Did you manage to solve your issue?

**Comment by turangojayev** [comment]
no, couldn't solve it, so had to use splash without Tor and luckily the domain I am crawling is not banning me, so far surviving without IP changes :)

**Comment by Gallaecio** [comment]
Nice :slightly_smiling_face: 

Since it’s [definitely possible](https://stackoverflow.com/a/45225377/939364), I’m closing this. If you decide to try again and continue to have issues, please use [StackOverflow](https://stackoverflow.com/tags/scrapy-scrapy) instead, we try to keep the issue tracker for issues in `scrapy-splash` itself.
