### ISSUE TITLE
Fetch number of results from Google News for a given time range

### ISSUE THREAD

**Issue by ghost** [scrapy-plugins/scrapy-splash#237]
I want to get the total number of news articles published for a list of keywords between a specified time period (Like last six months).

I've tried to use scrapy library to scrap google news but I'm unable to get results for the specified time period using the below code:

```
import scrapy

class QuotesSpider(scrapy.Spider):
    name = 'quotes'
    allowed_domains = ['google.com']
    start_urls = ['https://www.google.com/search?tbs=cdr%3A1%2Ccd_min%3A1%2F1%2F2019%2Ccd_max%3A8%2F1%2F2019&tbm=nws&ei=1tJXXfHLM4-S9QO07onwCg&q=%22Apple+Inc%22&oq=%22Apple+Inc%22&gs_l=psy-ab.3..0l3.48094.50359.0.51273.9.9.0.0.0.0.318.893.0j2j1j1.4.0....0...1c.1.64.psy-ab..6.3.752....0.2cwnwIbhfS4']

def parse(self, response):
    item = {
        'search_title': response.css('input#sbhost::attr(value)').get(),
        'results': response.css('#resultStats::text').get(),
    }
    yield item
```
I want to create a data frame as final output with the entity and number of results found on google news.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.
