### ISSUE TITLE
js in lua script doesn't run at all

### ISSUE THREAD

**Issue by zorro-gridi** [scrapy-plugins/scrapy-splash#238]
Hi there, this is my lua script blow:
script = '''
function main(splash, args)

  assert(splash:go(args.url))
  assert(splash:wait(args.wait))
  
  js = string.format("document.querySelector('#pg_paper_Performance #next_paper_Performance span').click();", args.page)
  splash:runjs(js)
  splash:wait(5)
  
  return splash:html()
end
'''
the problem is when I run it in "SplashRequest", the js part didn't run at all, so i always got the first page table content, could you help me out?thank a lot!!!

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.

**Comment by sortafreel** [comment]
Could you provide a URL to test it? Did you test it with local Splash (localhost:8050 through Docker)?

**Comment by sortafreel** [comment]
Could you provide a URL to test it? Did you test it with local Splash (localhost:8050 through Docker)?

> Hi there, this is my lua script blow:
> script = '''
> function main(splash, args)
> 
> assert(splash:go(args.url))
> assert(splash:wait(args.wait))
> 
> js = string.format("document.querySelector('#pg_paper_Performance #next_paper_Performance span').click();", args.page)
> splash:runjs(js)
> splash:wait(5)
> 
> return splash:html()
> end
> '''
> the problem is when I run it in "SplashRequest", the js part didn't run at all, so i always got the first page table content, could you help me out?thank a lot!!!
