### ISSUE TITLE
Scraping a site with recaptcha challange

### ISSUE THREAD

**Issue by sjaanus** [scrapy-plugins/scrapy-splash#239]
Getting this message and not able to parse site.

> Please upgrade to a supported browser to get a reCAPTCHA challenge.

Is there a way to set some parameter, so recaptcha accepts splash as supported browser?

**Comment by sjaanus** [comment]
Ok, setting user agent solves this problem. Now it actually asks me to solve the puzzle. Damn, so im cooked.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.
