### ISSUE TITLE
Scraping with splash and luminatii

### ISSUE THREAD

**Issue by anthonysanchezmk** [scrapy-plugins/scrapy-splash#240]
I'm trying to use luminatii for my proxy and splash to render the javascript, but my luminatii can't access the splash to render the javascript. I'm getting a 403. I guess a clarification that could help as well is, should my proxy be called first then splash is called through proxy, or should it be splash url being called, which then uses proxy to make request to website. Thank you for taking the time.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.
