### ISSUE TITLE
No results at "Server listening on http://0.0.0.0:8050"

### ISSUE THREAD

**Issue by mgrazianoc** [scrapy-plugins/scrapy-splash#248]
I'm on Windows using Docker tool box.

When I run `docker run -it -p 8050:8050 --rm scrapinghub/splash`, I receive the message `Server listening on http://0.0.0.0:8050`,as it should be. But when I go to the address, the only thing that returns is `ERR_ADDRESS_INVALID`, the page isn't loading. 

I try to search for this problem, changing the `SPLASH_URL` on my `settings.py` according to my Docker IP adress, but still with no sucess. The reason I'm intereseting in fixing this issue on my machine is because when I crawl with my spider, it just does nothing, i.e., the logging info returns:

` [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)`

Any ideias on how I messed this up? Thanks!

**Comment by mgrazianoc** [comment]
I've managed to understand the problem. 

I have to change my `SPLASH_URL ` to my `docker-engine ip`. I didn't help-me me with the logging problem, but at least helped me to uderstand the causes from the `ERR_ADDRESS_INVALID`. Now I can debbug my code knowing that Scrappy is running perfectly normal.

[StackOverflow helped me](https://stackoverflow.com/questions/59606885/scrapy-splash-no-results-at-server-listening-on-http-0-0-0-08050?) resolving this issue.

**Comment by mgrazianoc** [comment]
I also resolve the problem in the log message. I was calling my fuction as `start_request`, when I should use `start_requests`, at plural.

**Comment by Gallaecio** [comment]
Shall we close this issue, then?

**Comment by mgrazianoc** [comment]
Yes
