### ISSUE TITLE
Got warning; ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead.

### ISSUE THREAD

**Issue by syamdev** [scrapy-plugins/scrapy-splash#253]
Hi, i got this warning after I ran the spider.

[py.warnings] WARNING: /usr/local/lib/python3.7/dist-packages/scrapy_splash/request.py:41: ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead.
  url = to_native_str(url)

I use Scrapy 2.0

**Comment by LILU-WEB** [comment]
I got the same WARNNING....Splash cant work...any solutions??

**Comment by Beenyaa** [comment]
Hi, I am also having the exact same issue... Is there a fix or get around? I am trying to scrape the Google Shopping tab.

**Comment by SherkinOne** [comment]
I changed by python version from 3.7 back to 2.7, and it seemed to work!

**Comment by edinhoadm** [comment]
I had the same issue. To fix it you need to change SPLASH_URL in the settings.py file. Replace the standard IP 'http://192.168.59.103:8050' by the IP you are using on the browser. In my case has HTTP://0.0.0.0:8050.

**Comment by samLozier** [comment]
+1 i also have this issue. 

in case it helps anyone, I was able to resolve it by making the following change. I can't speak for any of the downstream implications of making this change, so use at your own risk: 

in the `scrapy_splash/request.py` file, line 41: 
from :
`url = to_native_str(url)`
to
`url = url`

**Comment by AugustoCL** [comment]
> +1 i also have this issue.
> 
> in case it helps anyone, I was able to resolve it by making the following change. I can't speak for any of the downstream implications of making this change, so use at your own risk:
> 
> in the `scrapy_splash/request.py` file, line 41:
> from :
> `url = to_native_str(url)`
> to
> `url = url`

where I find that folder?

**Comment by voxum** [comment]
Also ran across this while moving to 3.7. 

Working off others comments, what I went with was 
Adding 
`from scrapy.utils.python import to_unicode`
to `scrapy_splash/request.py`

then on line 41 change

`url = to_native_str(url)`
to
`url = to_unicode(url)`

**Comment by Rafiot** [comment]
@Gallaecio is there a chance to see a new release of scrapy-splash? I don't really mind packaging my own, but it's a bit annoying.

**Comment by Gallaecio** [comment]
This issue has not been fixed yet, so a new release would not help. Or maybe I’m missing something?

**Comment by Rafiot** [comment]
`to_native_str` is an alias to `to_unicode` in scrapy, with a deprecation warning: https://github.com/scrapy/scrapy/blob/5e9cc3298be4ca1146d68098899365b334706db8/scrapy/utils/python.py#L113

So just renaming the call in scrapy-splash will fix it. I'm happy to do a PR, if it helps.

Also, just in general, if you're interested in a PR that cleans up the lib and makes it python3 only, let me know, I'm happy to do that.

**Comment by Gallaecio** [comment]
That would be great.

I do expect us to have at least 1 more release with Python 2 support, so a PR only focused on this specific issue would be best.

**Comment by Rafiot** [comment]
The PR should work fine. The test suite was already broken with scrapy 2.0, and I don't know the project well enough to fix that, sorry.

I assumed the support of scrapy < 1.1.0 is not a requirement anymore.
