### ISSUE TITLE
No docker installation?

### ISSUE THREAD

**Issue by alexxsanchezm** [scrapy-plugins/scrapy-splash#257]
I found docker is very useful tool but now everybody wants to use it. I my case I hate use docker if I don't needed. I think the idea behind docker is to simplify configs around something. I would love use docker if the setup is too heavy. But for this??? come on!. We already have Virtual Envs that should be enough.

**Comment by lopuhin** [comment]
> We already have Virtual Envs that should be enough.

Yes I agree, since it's a pure python library. Splash itself has docker support. I hope you don't mind me closing the issue.
