### ISSUE TITLE
not helpful error msg

### ISSUE THREAD

**Issue by n1xqe** [scrapy-plugins/scrapy-splash#273]
Hi.
I created a scrapy project and wanted to use splash as js rendering service. In my case, the scrapy project is only a subfolder. If I call the spider from the parent folder scrapy started correctly and the spider too. But then is there an error in the parse function. The error is a Keyerror which contains something like 'HTMLRespons has no data[...]'. This error only raised if I called the scrapy project/spider from the parent folder. It is possible, that this isn't a scrapy-splash error but all related to scrapy works correctly. If it is a scrapy-splash error could you please raise a more clear error message?

**Comment by Gallaecio** [comment]
Could you please provide the steps to reproduce the error and a traceback of the error?

**Comment by n1xqe** [comment]
I solved the issue. Scrapy itself (twisted) was the problem.
