### ISSUE TITLE
fail to render a JS webpage

### ISSUE THREAD

**Issue by rogeronline** [scrapy-plugins/scrapy-splash#278]
fail to render the following page
https://www.lexusserramonte.com/new-inventory/index.htm

see following screen shot, it has no content at all
![Screen Shot 2021-01-12 at 5 41 09 PM](https://user-images.githubusercontent.com/1770479/104400982-27288b80-5508-11eb-9236-52c42cd85bcd.png)

i am running splash in disable-private-mode
`docker run -it -p 8050:8050 scrapinghub/splash --disable-private-mode`

can anybody take a look and shed a light on this...

**Comment by Gallaecio** [comment]
Closing in favor of https://github.com/scrapinghub/splash/issues/1095
