### ISSUE TITLE
Can one ScrapySplash server handle multiple SpashRequests from multiple Spiders?

### ISSUE THREAD

**Issue by fritz-0** [scrapy-plugins/scrapy-splash#279]
I have a Spider that crawls multiple URLs (100+) and I plan using both Requests and SplashRequests as the website needs JavaScript rendering. And, I am thinking of running Spiders simultaneously for the URLs.

Please note that my Spider does a lot of series of callbacks.

Is ScrapySplash capable of handling the simultaneous requests that can come from the multiple Spiders?

That is, even if there is only on Scrapy-Splash running (via Docker) on localhost:8050? If yes, how can I implement such or are there better alternatives?

**Comment by Gallaecio** [comment]
This probably makes more sense in https://github.com/scrapinghub/splash, since it is about the server, and not the Scrapy plugin to use the server easily from Scrapy.
