### ISSUE TITLE
Callback Function Parameters

### ISSUE THREAD

**Issue by colingoodman** [scrapy-plugins/scrapy-splash#288]
I am attempting to pass some parameter to a function I defined and am feeding to the callback parameter in the SplashRequest object: `yield SplashRequest(response.urljoin(state_link), callback=self.parse_state, args={'wait': 1})`

As per [this StackOverflow page](https://stackoverflow.com/questions/32252201/passing-a-argument-to-a-callback-function), scrapy defines a `meta` field that scrapy-splash doesn't also have. I wasn't able to find any information on a similar field on the documentation. 

Is there a way to pass parameters to a callback function in scrapy-splash?

**Comment by apchirinoc** [comment]
Did you get how to do that?
