### ISSUE TITLE
Please Can we do a new release for all the changes merged in master since 8.0 in October'21

### ISSUE THREAD

**Issue by DharmeshPandav** [scrapy-plugins/scrapy-splash#307]
https://github.com/scrapy-plugins/scrapy-splash/compare/0.8.0...master

One that's nagging me is the following warning in my logs, for which the fix was applied in this PR https://github.com/scrapy-plugins/scrapy-splash/pull/269.

 if not major, can we please have a minor release 0.8.1 ?
```
[py.warnings] /usr/local/lib/python3.10/site-packages/scrapy_splash/[request.py:42](http://request.py:42/): ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead. Less

  url = to_native_str(url)
```

**Comment by mrhaanraadts** [comment]
It's no warning anymore.
to_native_str was removed from [Scrapy 2.8.0](https://docs.scrapy.org/en/latest/news.html#scrapy-2-8-0-2023-02-02)

**Comment by DharmeshPandav** [comment]
Possibly not being maintained @kmike  @pablohoffman

**Comment by Gallaecio** [comment]
Oops. On it…

**Comment by Gallaecio** [comment]
[0.9.0 is out now](https://github.com/scrapy-plugins/scrapy-splash/releases/tag/0.9.0), thanks!

**Comment by DharmeshPandav** [comment]
Thanks :)
