### ISSUE TITLE
Timeouts in scrapyjs 

### ISSUE THREAD

**Issue by shafaq** [scrapy-plugins/scrapy-splash#36]
I am a little nervous to post this but can you please see at this SO question:
http://stackoverflow.com/questions/34656424/scrapyjs-example-from-official-github-not-running
I exactly have the same problem. It constantly times out. Though I used solutions from these: 
- http://stackoverflow.com/questions/30345623/scraping-dynamic-content-using-python-scrapy/30378765#30378765
- http://stackoverflow.com/questions/32141967/how-can-scrapy-deal-with-javascript

Even opening splash in browser and rendering a simple page like google.com fails as well. I just pulled the new image for docker but it is not working. 

PS. I am nervous because with everyone else it seems to work fine. :)

**Comment by kmike** [comment]
Hey @shafaq,

It looks like either Splash configuration error or a problem with a website. Maybe you're trying to access Splash at a wrong IP address, or maybe you haven't exposed the port when running docker container. I don't think scrapy-splash may cause this timeout; Splash bug tracker (or Splash gitter chat) is a better place to discuss this issue.
