### ISSUE TITLE
Add some Splash specific retry logic to scrapy-splash

### ISSUE THREAD

**Issue by pawelmhm** [scrapy-plugins/scrapy-splash#37]
When Splash returns some error it is just retried by Scrapy without printing error messages. This is a pain because if you get 400 from Splash you should  be able to see error message immediately, usually 400 means some error from your side so you must know what you did wrong. WIth current middleware you just get 400 in logs and usually this is retried by Scrapy retry middleware, there is no quick and easy way to see what error you got.

**Comment by kmike** [comment]
+1, that's be a nice feature

**Comment by kmike** [comment]
In upcoming Scrapy 1.1 HTTP 400 is not longer in default RETRY_HTTP_CODES, and for other errors it makes sense to retry.

**Comment by kmike** [comment]
I've added logging of HTTP 400 Splash responses to scrapy-splash; it is enabled by default.

**Comment by kmike** [comment]
As HTTP 400 requests are not retried by scrapy now, and HTTP 400 error contents is logged by scrapy-splash I think this ticket can be closed as "fixed".
