### ISSUE TITLE
Warnings in Scrapy 1.0.5

### ISSUE THREAD

**Issue by tsouras** [scrapy-plugins/scrapy-splash#38]
I see the following warnings:
py.warnings - WARNING - /home/tsouras/Desktop/web2py/gluon/custom_import.py:74: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.
  return NATIVE_IMPORTER(oname, globals, locals, fromlist, level)

2016-02-27 23:20:35,840 - py.warnings - WARNING - /home/tsouras/Desktop/web2py/gluon/custom_import.py:74: ScrapyDeprecationWarning: Module `scrapy.dupefilter` is deprecated, use `scrapy.dupefilters` instead
  return NATIVE_IMPORTER(oname, globals, locals, fromlist, level

2016-02-27 23:20:35,841 - py.warnings - WARNING - /home/tsouras/Desktop/web2py/gluon/custom_import.py:74: ScrapyDeprecationWarning: Module `scrapy.contrib.httpcache` is deprecated, use `scrapy.extensions.httpcache` instead
  return NATIVE_IMPORTER(oname, globals, locals, fromlist, level)

2016-02-27 23:20:35 [py.warnings] WARNING: /home/tsouras/Desktop/web2py/gluon/custom_import.py:74: ScrapyDeprecationWarning: Module `scrapy.contrib.httpcache` is deprecated, use `scrapy.extensions.httpcache` instead
  return NATIVE_IMPORTER(oname, globals, locals, fromlist, level)

According to http://doc.scrapy.org/en/latest/news.html
the logging and the names of some modules have been changed on Scrapy version 1.0.0

I use scrapy 1.0.5 and linux Mint

**Comment by kmike** [comment]
Warning is at `/home/tsouras/Desktop/web2py/gluon/custom_import.py` - what is it? Why is it importing deprecated Scrapy modules?

**Comment by tsouras** [comment]
I run scrapy from a module of web2py framework.
I use the following code in that module:

def runScraper(spider_name):
    from scrapy.crawler import Crawler, CrawlerProcess
    from scrapy.settings import Settings
    settings=Settings(values={'BOT_NAME':spider_name, 'LOG_LEVEL':'INFO'}) 
    if spider_name=='LeagueScraper':
        crawler = Crawler(LeagueScraper)
    elif spider_name=='MatchFinder':
        crawler = Crawler(MatchFinder)
    else:
        return "%s is an unknown spider name" % spider_name
    crawlerProcess = CrawlerProcess(settings=settings)  
    crawlerProcess.crawl(crawler)
    crawlerProcess.start() # the script will block here until the crawling is finished

**Comment by kmike** [comment]
I'm not sure we can do anything here. web2py imports deprecated scrapy modules for whatever reason (maybe to provide module reloading?), so scrapy issues warnings. I'd say web2py shouldn't do that. Maybe there is a way in web2py to avoid this, I don't know. You can use warning [filters](https://docs.python.org/2/library/warnings.html#warnings.filterwarnings) to suppress these warnings if they are annoying. Hope this helps.

It is certainly not a problem with scrapy-splash implementation (web2py imports deprecated modules from Scrapy), so I'm closing this ticket.

**Comment by tsouras** [comment]
I think that I found what is the problem. I installed scrapyjs from pip. The version that I have is not the latest. 
For example in the version that I have, in file dupefilter.py there is the command "from scrapy.dupefilter import RFPDupeFilter". In the latest version of githb in the same file there is the command "from scrapy.dupefilters import RFPDupeFilter". 

I installed scrapyjs using pip today.

**Comment by kmike** [comment]
@tsouras yeah, this explains it.
