### ISSUE TITLE
Why ScrapyJS has Lua as scripting language and not Python?

### ISSUE THREAD

**Issue by shafaq** [scrapy-plugins/scrapy-splash#40]
Its not an issue just a query.

I was just wondering why ScrapyJS has Lua as scripting language and not Python?
What superiority Lua provide to Python. 
Would it not be nice to have execute endpoint for python as well?
# justWondering :)

**Comment by kmike** [comment]
Hey @shafaq,

See the original Splash ticket for motivation: https://github.com/scrapinghub/splash/issues/117

Splash internals allow to add Python scripting in future; it provides BrowserTab object which can be used in Python scripts (it is used e.g. in Portia), but that's internal and not documented. I agree that'd be nice to have official Python scripts support. But that's quite a lot of work and we don't plans to implement it anytime soon. But if someone wants to help contributions are welcome. Splash participates in Google Summer of Code 2016 (to be started soon); I think Python scripting support is a reasonable GSoC project.

**Comment by davidkhess** [comment]
In the original ticket, it seems that sandboxing was an important requirement? I'm curious as to why? Was there concern that a control script could be subverted by a page?

Or was it to protect the Splash process from a submitted script?

**Comment by kmike** [comment]
@davidkhess sandbox is mainly for protecting Splash process from a submitted script, and for protecting concurrently executing scripts from each other.
