### ISSUE TITLE
scrapy_splash.SplashMiddleware priority_adjust value should be taken from settings RETRY_PRIORITY_ADJUST

### ISSUE THREAD

**Issue by sliwinski-milosz** [scrapy-plugins/scrapy-splash#64]
In scrapy for default request we can set priority_adjust value by setting RETRY_PRIORITY_ADJUST in settings.

For scrapy-splash priority_adjust is a hardcoded value equal to 5. Should be taken from RETRY_PRIORITY_ADJUST.

**Comment by kmike** [comment]
Hey @sliwinski-milosz,

Why do you need to change this value?
It is needed for a specific reason: 
1. request is sent to scheduler when you yield it from a spider callback; priority is not adjusted;
2. after processing all requests according to their priority request is fetched from scheduler and sent to to the downloader;
3. but before getting to downloader (i.e. before scrapy actually starts downloading the request) this request is sent through downloader middlewares. So `process_request` method of SplashMiddleware is called. 
4. `process_request` modifies this request - it changes request.body and request.method. When request is modified by a downloader middleware it is not passed to downloader, it is sent back to the scheduler. So the request is in scheduler again.

Here we have a problem - the request which was the top according to its priority (and so which was fetched from scheduler) is sent to the scheduler again. With default settings it is sent to the back of the queue for all requests with the same priority. 

It causes several problems:
1. downloader middleware sets `cookies` argument; if request processing is delayed cookies can get stale;
2. new request body can be large; if we process all requests using SplashMiddleware first and download them next then we'll have to keep these request bodies in queue for longer; it means larger disk queue sizes.

So to fix that SplashMiddleware changes the priority of the rescheduled request (+5 in master; I'm going to increase it in https://github.com/scrapy-plugins/scrapy-splash/pull/63). After this change when processed request is sent back to the scheduler it won't be there for too long, which should help with cookie and disk storage issues.

**Comment by sliwinski-milosz** [comment]
In my scraper I use some specific way of handling request by priorities -> and I added highest priority as well which is max integer. Because I was not aware of above logic I went to exceptions regarding to big value for priority.

But anyway looks like my case is very specific. I can handle it somehow in my code. If that logic is needed, lets keep it there :)
Closing bug.
