### ISSUE TITLE
SplashFormRequest.from_response marked as undefined in eclipse

### ISSUE THREAD

**Issue by sliwinski-milosz** [scrapy-plugins/scrapy-splash#66]
Eclipse SplashFormRequest.from_response is marked red as "Undefined variable from import: from_response" - for scrapy-splash 0.4.

But it works during script execution.

**Comment by kmike** [comment]
It must be a problem with Eclipse code completion - PyCharm gets it right. I don't think we can (or should) do anything in scrapy-splash.
