### ISSUE TITLE
After enable the DEFAULT_REQUEST_HEADERS from settings.py ,scrapy splash does not work well 

### ISSUE THREAD

**Issue by BruceDone** [scrapy-plugins/scrapy-splash#67]
Hi all:
    after i enable the DEFAULT_REQUEST_HEADERS from the settings.py ,when SplashRequest make the request header ,it should use 
 `{'Content-Type': 'application/json'}`  

> Splash is controlled via HTTP API. For all endpoints below parameters may be sent either as GET arguments or encoded to JSON and POSTed with Content-Type: application/json header.

since the [splash doc](http://splash.readthedocs.org/en/stable/api.html#examples) referred here: 

but the header will be replaced by the default settings.py value ,then the whole request does not work 
well .

**Comment by kmike** [comment]
@BruceDone could you please provide an example? What's in your DEFAULT_REQUEST_HEADERS and how are you using SplashRequest? What scrapy-splash version do you use?

**Comment by BruceDone** [comment]
pip list 
`scrapy-splash (0.5)`
`Scrapy (1.0.5)`

the settings.py:

```
DEFAULT_REQUEST_HEADERS =
 {
    'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
    ,'Accept-Encoding':'gzip, deflate, sdch'
    ,'Accept-Language':'zh-CN,zh;q=0.8,en;q=0.6'
    ,'Connection':'keep-alive'
    ,'Host':'channel.jd.com'
    ,'Referer':'http://list.jd.com/list.html?cat=1315%2C1343%2C9715&go=0'
    ,'Cache-Control':'max-age=0'
    ,'Upgrade-Insecure-Requests':'1'
    ,'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36'
}
```

the code here:

```
# -*- coding: utf-8 -*-
from scrapy import Request
from scrapy.spiders import Spider
from scrapy_splash import SplashRequest
from scrapy_splash import SplashMiddleware



class WeiXinSpider(Spider):
    name = 'weixin'
    # main address since it has the fun list of the products
    start_urls = [
        'http://weixin.sogou.com/weixin?page={}&type=2&query=%E4%B8%AD%E5%9B%BD'.format(a) for a in xrange(1,10)
    ]

    # allowed_domains = [
    #     'sogou.com'
    # ]

    def start_requests(self):
        for url in self.start_urls:
            yield SplashRequest(url
                                ,self.parse
                                ,args={'wait':'0.5'}
                                )
        pass

    def parse(self, response):
        self.logger.info('now you can see the url %s' % response.url)
        div_results = response.xpath('//div[@class="results"]/div')
        if not div_results:
            self.logger.error(msg='there is not any body in the %s' % response.body)
            return
        for div_item in div_results:
            title = div_item.xpath('descendant::div[@class="txt-box"]//h4//text()')
            if title:
                txt = ''.join(title.extract())
                yield {'title':txt}
```

i think i have already find the problem ,since the url i request does not match the headers host i post ,then the splash sever will not return the right content i need ,thanks for quick response ,please close this issue

**Comment by kmike** [comment]
Yeah, it doesn't make sense to include Host header; it is set automatically by Splash to a correct value. Referer should be handled by a scrapy middleware, so it is better to remove it as well. Does it work without these headers?

**Comment by BruceDone** [comment]
Yes ,after i remove the Host from headers ,it runs successfully ,thanks for reply :)

**Comment by kmike** [comment]
Thanks for checking that!
