### ISSUE TITLE
"docker run -it -p 8050:8050 scrapinghub/splash --max-timeout 3600" doesn't work

### ISSUE THREAD

**Issue by bigfuji** [scrapy-plugins/scrapy-splash#69]
`2016-04-27 15:18:54.748787 [events] {"_id": 140682213021232, "client_ip": "172.17.42.1", "args": {"cookies": [], "lua_source": "\nfunction main(splash)\n    splash:go(splash.args.url)\n    splash:wait(1)\n    return splash:html()\nend\n", "url": "http://www.google.com/all", "uid": 140682213021232, "headers": {"Accept-Language": "en", "User-Agent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}}, "status_code": 200, "fds": 41, "maxrss": 140476, "method": "POST", "path": "/execute", "qsize": 0, "user-agent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36", "rendertime": 18.67064356803894, "timestamp": 1461770334, "active": 0, "load": [0.21, 0.35, 0.41]}
2016-04-27 15:18:54.749018 [-] "172.17.42.1" - - [27/Apr/2016:15:18:53 +0000] "POST /execute HTTP/1.1" 200 258608 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36"
`

It seems that the timeout argument is still 30 not 3600

**Comment by kmike** [comment]
`docker run -it -p 8050:8050 scrapinghub/splash --max-timeout 3600` sets maximum allowed value for  `timeout` parameter, but it doesn't change default timeout value (30s). Are you passing `timeout` argument to Splash?

**Comment by kmike** [comment]
like this:

``` py
yield SplashRequest(url, self.parse, args={'wait': 0.5, 'timeout': 120})
```

**Comment by bigfuji** [comment]
OK,it works!
Thank you very much!

**Comment by kmike** [comment]
No problems, glad it worked!
