### ISSUE TITLE
Provide helpers for common tasks

### ISSUE THREAD

**Issue by kmike** [scrapy-plugins/scrapy-splash#8]
Examples: 
- render HTML;
- render a screenshot;
- do a request to render.json, decode the result;
- run Lua script.

I think these helpers could be scrapy.Request subclasses.
See also: https://github.com/scrapinghub/scrapyjs/blob/master/scrapyjs/request.py

**Comment by CestDiego** [comment]
^ this

**Comment by kmike** [comment]
There is now SplashRequest and custom Splash responses. We can add more helpers, but they deserve separate tickets.
