### ISSUE TITLE
Splash won't execute lua script

### ISSUE THREAD

**Issue by icyc9** [scrapy-plugins/scrapy-splash#83]
Hey,

I have ran across an issue in which my Lua script refuses to execute. The returned response from the ScrapyRequest call seems to be an HTML body, while i'm expecting a document title. I am assuming that the Lua script is never being called as it seems to have no apparent effect on the response. I have dug a lot through the documentation and can't quite seem to figure out what is missing here. Does anyone have any suggestions?

```
from urlparse import urljoin

import scrapy
from scrapy_splash import SplashRequest


GOOGLE_BASE_URL = 'https://www.google.com/'
GOOGLE_QUERY_PARAMETERS = '#q={query}'
GOOGLE_SEARCH_URL = urljoin(GOOGLE_BASE_URL, GOOGLE_QUERY_PARAMETERS)

GOOGLE_SEARCH_QUERY = 'example search query'


LUA_SCRIPT = """
function main(splash)
    assert(splash:go(splash.args.url))
    return splash:evaljs("document.title")
end
"""

SCRAPY_CRAWLER_NAME = 'google_crawler'
SCRAPY_SPLASH_ENDPOINT = 'render.html'
SCRAPY_ARGS = {
    'lua_source': LUA_SCRIPT
}


def get_search_url(query):
    return GOOGLE_SEARCH_URL.format(query=query)


class GoogleCrawler(scrapy.Spider):
    name=SCRAPY_CRAWLER_NAME
    search_url = get_search_url(GOOGLE_SEARCH_QUERY)

    def start_requests(self):

        response = SplashRequest(self.search_url,
            self.parse, endpoint=SCRAPY_SPLASH_ENDPOINT, args=SCRAPY_ARGS)

        yield response


    def parse(self, response):
        doc_title = response.body_as_unicode()
        print doc_title
```

**Comment by kmike** [comment]
Hey Robert,

For Lua scripts you should use /execute endpoint, not /render.html endpoint.

**Comment by icyc9** [comment]
@kmike Hey, I have changed the endpoint to execute. Still no luck.  Is there anything else that may  be causing this?

**Comment by kmike** [comment]
I'm not sure what caused the problem for you. Could you returning `{title=splash:evaljs("document.title")}` from Splash script, and then checking what's in `response.data` (see https://github.com/scrapy-plugins/scrapy-splash#responses)?

**Comment by kmike** [comment]
Actually, you may just check what's in response.data without changing the Lua script.

**Comment by icyc9** [comment]
@kmike It appears that there is no 'data' attribute. 

`Traceback (most recent call last):
  File "/Users/rob/solvely/SolvelyAlgorithm/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/rob/solvely/SolvelyAlgorithm/splash.py", line 40, in parse
    print response.data
AttributeError: 'HtmlResponse' object has no attribute 'data'
`

**Comment by kmike** [comment]
Could you re-check the scrapy-splash setup? There is an awful lot of steps to follow: https://github.com/scrapy-plugins/scrapy-splash#configuration

**Comment by icyc9** [comment]
I have already populated a settings.py file with the following:

```
SPLASH_URL = 'http://localhost:8050'

DOWNLOADER_MIDDLEWARES = {
    'scrapy_splash.SplashCookiesMiddleware': 723,
    'scrapy_splash.SplashMiddleware': 725,
    'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 810,
}

SPIDER_MIDDLEWARES = {
    'scrapy_splash.SplashDeduplicateArgsMiddleware': 100,
}
```

@kmike Not sure if i am missing anything.

**Comment by ilyaperepelitsa** [comment]
@RobertChristopher did you figure it out? dealing with a similar problem. I know that my lua script has a bunch of "wait"s that get executed when I run it in http://127.0.0.1:8050 render but not in scrapy thing=(((((

**Comment by kmike** [comment]
@ilyaperepelitsa do you have the same traceback ("'HtmlResponse' object has no attribute 'data'")? Are you using SplashRequest?

**Comment by JavierRuano** [comment]
I have the same issue, according to manual render.html -> render.json. 
And return {title = splash:evaljs("document.title")}
response.data['title'].
I have tried that but my issue persists.
Do you have solved it?

**Comment by JavierRuano** [comment]
I think the solution is the same https://github.com/scrapy-plugins/scrapy-splash/issues/194 . but documentation says the jquery has a special form to load script.

**Comment by ahmad-rzk** [comment]
Having the same problem ,
AttributeError: 'SplashTextResponse' object has no attribute 'data'

code:

```
lua_script="""
            function main(splash, args)
                local ok, reason = splash:go(args.url)
                ...
                splash:wait(math.random(5, 10))
                return {
                    png = splash:png(),
                }
            end
        """
        yield SplashRequest(
        url = self.login_url,
        endpoint="run",
        args={
            "lua_source": lua_script,
            "user_name" : self.email, 
            "user_password" : self.password,
        },
        callback = self.after_login,
        errback = self.parse_error,
    )

def after_login(self,response):
        self.logger.info(type(response)) # <class 'scrapy_splash.response.SplashTextResponse'> i guees it shouldn't be of this type
        imgdata = base64.b64decode(response.data['png']) # Error happens here
        filename = 'MyWebsiteHome.png'
        with open(filename, 'wb') as f:
            f.write(imgdata)
        return

```

**Comment by SVGalich** [comment]
I have the same problem. SplachRequest does not execute lua script.
In Splash browser my lua script works fine. It must be executed in several seconds due to the some "splash:wait(1)" lines. But SplachRequest yields response with url's html.text as soon as starts.

Here is my code:

	def parse(self, response):
		<...>
			script = """
function main(splash)
splash.resource_timeout = 10.0
assert(splash:go(splash.args.url))
splash:wait(2)
local element = splash:select('a.phone-trigger')
local bounds = element:bounds()
element:mouse_click{x=bounds.width/2, y=bounds.height/2}
splash:wait(2)
return splash:html()
end
"""
			args = {'lua_source': script,
					'timeout': 10,
					'resource_timeout': 10,
					'wait': 5,
					'har': 1,
					'html': 1,
					}
			yield SplashRequest(url=buyers_link,
								callback=self.parse_buyer,
								cb_kwargs=data,
								endpoint='execute',
								args=args,
								dont_filter = True
								)
    def parse_buyer(self, response,
	                Title,
					Name,
	                Contact,
	                Region
	                ):
<...>

And no matters what is in lua script SplashRequest always does the same.
I did everything exectly with documentation: run Docker, install all required packages, make these project settings:
SPLASH_URL = 'http://localhost:8050'
DOWNLOADER_MIDDLEWARES = {
                        'scrapy_splash.SplashCookiesMiddleware': 723,
                        'scrapy_splash.SplashMiddleware': 725,
                        'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 810
                       }
SPIDER_MIDDLEWARES = {
                        'scrapy_splash.SplashDeduplicateArgsMiddleware': 100
                    }
DUPEFILTER_CLASS = 'scrapy_splash.SplashAwareDupeFilter'
HTTPCACHE_STORAGE = 'scrapy_splash.SplashAwareFSCacheStorage'

But it works like there is no splash at all! Please, help me in solving this problem!

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy-splash) to ask this type of questions.
