### ISSUE TITLE
how to process parts of javascript sources to avoid 504 timeout?

### ISSUE THREAD

**Issue by rc1021** [scrapy-plugins/scrapy-splash#85]
thanks owner, scrapy-splash is nice plugins.

there are many reasons got 504 timeout, one of reason is render js sources late.

Would you please tell me how to just process parts of javascript sources?

**Comment by kmike** [comment]
Hey @Easter1021,

There is some information about that in Splash docs: http://splash.readthedocs.io/en/stable/faq.html#i-m-getting-lots-of-504-timeout-errors-please-help. Hope it helps.
