### ISSUE TITLE
QHttpNetworkConnectionPrivate::_q_hostLookupFinished could not dequeu request

### ISSUE THREAD

**Issue by aalavender** [scrapy-plugins/scrapy-splash#86]
I run scrapy-splash with docker on ubuntu 14.04
I receive  many "QHttpNetworkConnectionPrivate::_q_hostLookupFinished could not dequeu request" in console 
and the memory used  increase  without stopping till the server is memry out

I don't known how to do?

**Comment by Gallaecio** [comment]
@aalavender Could you please close this issue and report it on https://github.com/scrapinghub/splash?
