### ISSUE TITLE
ValueError for cookies with null values

### ISSUE THREAD

**Issue by lukemaxwell** [scrapy-plugins/scrapy-splash#93]
It would be nice if Splash could handle cookies fields containing null values. 

Currently ValueError is raised:
https://github.com/scrapy-plugins/scrapy-splash/blob/master/scrapy_splash/utils.py#L44

**Comment by Gallaecio** [comment]
@kmike I believe you fixed this in 225793bab7f44241144bd65811669f6cbb5d6b9d
