### ISSUE TITLE
QXcbIntegration: Cannot create platform offscreen surface, neither GLX nor EGL are enabled

### ISSUE THREAD

**Issue by scum0514** [scrapy-plugins/scrapy-splash#94]
Hi all:

When i crawled this page "http://www.mouser.cn/Electronic-Components",
Docker logs show errors below:
```
  QXcbIntegration: Cannot create platform offscreen surface, neither GLX nor EGL are enabled
  QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
  QXcbIntegration: Cannot create platform offscreen surface, neither GLX nor EGL are enabled
  QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
```
The website thinks javascript is not running and redirect to "http://www.mouser.cn//distil_r_captcha.html".
Anyone help?

PS:Other pages is ok, no 'QXcbIntegration' error shown.

**Comment by kmike** [comment]
Hey @scum0514, 
I think this issue belongs to Splash, not to scrapy-splash. 
I'm not sure if that's the reason, but it looks like website uses some browser feature which is not available in Splash docker image.
