### ISSUE TITLE
Crawlera integration

### ISSUE THREAD

**Issue by m2jobe** [scrapy-plugins/scrapy-splash#97]
Has anyone been able to integrate scrapy-splash with crawlera?

**Comment by kmike** [comment]
Hey @m2jobe,

To use scrapy-splash with Crawlera you need to create a Lua script (an example is in crawlera docs: https://doc.scrapinghub.com/crawlera.html#using-crawlera-with-splash), and then use /execute andpoint with SplashRequest, passing this script. 

So it should be something like that (note that I combined a script from Crawlera docs and a script from scrapy-splash README in order to enable cookies, response headers, etc.):

```lua
-- myscript.lua
function main(splash)
    -- begin example from crawlera docs
    local host = "proxy.crawlera.com"
    local port = 8010
    local user = splash.args.apikey
    local password = ""
    local session_header = "X-Crawlera-Session"
    local session_id = "create"

    splash:on_request(function (request)
        request:set_header("X-Crawlera-UA", "desktop")
        request:set_header(session_header, session_id)
        request:set_proxy{host, port, username=user, password=password}
    end)

    splash:on_response_headers(function (response)
        if response.headers[session_header] ~= nil then
            session_id = response.headers[session_header]
        end
    end)
    -- end example from crawlera docs

    -- customized render script inspired by scrapy-splash examples
    splash:init_cookies(splash.args.cookies)
    assert(splash:go{
        splash.args.url,
        headers=splash.args.headers,
        http_method=splash.args.http_method,
        body=splash.args.body,
    })
    assert(splash:wait(0.5))

    local entries = splash:history()
    local last_response = entries[#entries].response
    return {
        url = splash:url(),
        headers = last_response.headers,
        http_status = last_response.status,
        cookies = splash:get_cookies(),
        html = splash:html(),
    }
end
```

Then in a spider you can load this script (or just put it into a string constant) and use SplashRequest to render it:

```python
import scrapy
from scrapy_splash import SplashRequest

with open('myscript.lua', 'rb') as f:
    lua_source = f.read().decode('utf8')


class MySpider(scrapy.Spider):
    # ...
    def my_parse(self, response):
        # ...
        yield SplashRequest(url, self.parse_result,
            endpoint='execute',
            cache_args=['lua_source'],
            args={
                'lua_source': script, 
                'apikey': "<YOUR_API_KEY>"
            },
       )
```

Hope this helps. I haven't actually tested the code above, but I think it should work :) You can tweak the script - the basic idea is to customize an example from Crawlera docs using suggestions from scrapy-splash README.

**Comment by m2jobe** [comment]
hey @kmike 

I get this error from splash following the above setup

 "error": "http470", "type": "LUA_ERROR"}, "description": "Error happened while executing Lua script", "error": 400, "type": "ScriptError"}

**Comment by m2jobe** [comment]
request:set_proxy{host, port, username=user, password=password}

Error is caused by this line, error 470 is crawlera's bad authentication response

**Comment by m2jobe** [comment]
Ok it turns out if youre on C10 plan you can't use X-Crawlera-UA so comment the line below out
 -- request:set_header("X-Crawlera-UA", "desktop")

And secondly you may need to increase your timeout 
request:set_header('X-Crawlera-Timeout', 40000)

**Comment by jovenjiang** [comment]
perfect!  It'll be of great assistance to me

**Comment by amarynets** [comment]
Hi @kmike I tried your example and [from official doc](https://github.com/scrapinghub/sample-projects) but it didn't help me. I created [issue](https://github.com/scrapinghub/sample-projects/issues/3) where describe more about it. The result is following: sometimes I got 200 response, but very rare and this response without Js. Most often I got empty result or message **Website crawl ban**
