### ISSUE TITLE
Could not find a version that satisfies the requirement scrapy-splash

### ISSUE THREAD

**Issue by zwl1619** [scrapy-plugins/scrapy-splash#98]
I am using scrapy `1.3` on windows `10`.
```
PS D:\scrapy> pip install scrapy-splash
Collecting scrapy-splash
  Could not find a version that satisfies the requirement scrapy-splash (from versions: )
No matching distribution found for scrapy-splash
```

**Comment by kmike** [comment]
Are you able to install other packages? It looks like pip configuration issue, or a temporary problem with pypi. You may get a bit more info by running `pip install -vvv scrapy-splash`.

**Comment by Gallaecio** [comment]
@kmike Should we close due to a lack of feedback?
